/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 세이브 데이터 HMAC-SHA256 서명 (키는 바이너리 내부) */
export declare function computeSaveSig(snapshot: string): string
/** 서명 검증 — 일치하면 true */
export declare function verifySaveSig(snapshot: string, sig: string): boolean
/** 초기 경기 상태 생성 */
export declare function startMatchNative(optionsJson: string): string
/** 주인공 인터랙티브 투구 (1구) */
export declare function stepPitchNative(stateJson: string, decisionJson: string): string
/** 경기 종료 처리 */
export declare function finishMatchNative(stateJson: string): string
/** 현재 주인공 투구 차례 여부 */
export declare function isProtagonistPitchingNative(stateJson: string): boolean
/** 다음 게임 페이즈 결정 (orchestrator) */
export declare function advanceGamePhaseNative(stateJson: string): string
/** 등판 트리거 충족 시점까지 자동 시뮬 */
export declare function simUntilEntry(stateJson: string): string
/** 게임 종료까지 자동 시뮬 */
export declare function simToGameEnd(stateJson: string): string
/** 반이닝 자동 시뮬 */
export declare function simHalfInning(stateJson: string): string
/** 감독 자동 마운드 방문 체크 */
export declare function autoMoundVisitNative(stateJson: string): string
/** 마운드 방문 적용 */
export declare function requestMoundVisitNative(stateJson: string): string
/** 주인공 강판 판단 */
export declare function shouldProtagonistExitNative(stateJson: string): string
/** 헤드리스 게임 시뮬 (튜닝 랩용) */
export declare function runSimpleGame(paramsJson: string): string
