/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 세이브 데이터 HMAC-SHA256 서명 (키는 바이너리 내부) */
export declare function computeSaveSig(snapshot: string): string
/** 세이브 데이터 암호화 → base64(nonce || ciphertext) */
export declare function encryptSaveNative(plaintext: string): string
/** 세이브 데이터 복호화 (구 평문 포맷 자동 감지) */
export declare function decryptSaveNative(ciphertext: string): string
/** 서명 검증 — 일치하면 true */
export declare function verifySaveSig(snapshot: string, sig: string): boolean
/** 초기 경기 상태 생성 */
export declare function startMatchNative(optionsJson: string): string
/** 주인공 인터랙티브 투구 (1구) */
export declare function stepPitchNative(stateJson: string, decisionJson: string): string
/** 경기 종료 처리 */
export declare function finishMatchNative(stateJson: string): string
/** 현재 주인공 투구 차례 여부 */
export declare function isProtagonistPitchingNative(stateJson: string): boolean
/** 다음 게임 페이즈 결정 (orchestrator) */
export declare function advanceGamePhaseNative(stateJson: string): string
/** 등판 트리거 충족 시점까지 자동 시뮬 */
export declare function simUntilEntry(stateJson: string): string
/** 게임 종료까지 자동 시뮬 */
export declare function simToGameEnd(stateJson: string): string
/** 반이닝 자동 시뮬 */
export declare function simHalfInning(stateJson: string): string
/** 감독 자동 마운드 방문 체크 */
export declare function autoMoundVisitNative(stateJson: string): string
/** 마운드 방문 적용 */
export declare function requestMoundVisitNative(stateJson: string): string
/** 주인공 강판 판단 */
export declare function shouldProtagonistExitNative(stateJson: string): string
/** 헤드리스 게임 시뮬 (튜닝 랩용) */
export declare function runSimpleGame(paramsJson: string): string
/** NPC 게임 헤드리스 시뮬 */
export declare function simGameNative(paramsJson: string): string
/** 오프시즌 전체 처리 */
export declare function runOffseasonNative(paramsJson: string): string
/** 고교 학년 진급 */
export declare function advanceGradesNative(paramsJson: string): string
/** NPC 주간 성장/하락 처리 */
export declare function npcCalcWeeklyGrowth(paramsJson: string): string
/** 신입생 벌크 생성 */
export declare function generateFreshmenNative(paramsJson: string): string
/** FA 시장 정산 — 등급·계약·보상선수를 한 번에 */
export declare function resolveFaMarketNative(paramsJson: string): string
/** 주간 수입·지출·세금. `money`에 더할 순현금을 낸다 */
export declare function calcWeeklyFinanceNative(paramsJson: string): string
/** 명성 연동 스폰서 오퍼. 학생·독립은 빈 결과 (아마추어 규정) */
export declare function calcSponsorOffersNative(paramsJson: string): string
/** 개인 트레이닝 구독 보너스 — **팀 자원에 반비례**한다 */
export declare function calcTrainingBonusNative(paramsJson: string): string
/** 시즌말 투자 정산. 원금 손실 가능, 전액 소실은 없음 */
export declare function resolveInvestmentNative(paramsJson: string): string
/** 사치품 소비 — 동료면 관계도, 자기 소비면 성격에 따라 명성 ± */
export declare function calcLuxuryNative(paramsJson: string): string
/** 전국대학선수쇼케이스 — 팀 추천 + 주목도 상위 + 구단 지명 세 경로 */
export declare function runShowcaseNative(paramsJson: string): string
/** 대학 올스타전(북 vs 남) — 포지션 쿼터 + 대학당 캡 */
export declare function runAllstarNative(paramsJson: string): string
/** 국가대표 발탁 — 그 해 대회가 없으면 빈 결과 */
export declare function selectNationalSquadNative(paramsJson: string): string
/** 국제대회 결과 — 경기는 시뮬하지 않고 대표팀 전력으로 순위를 뽑는다 */
export declare function simulateTournamentNative(paramsJson: string): string
/** 드래프트 후보 선정 — 졸업생 + 대학 재학 얼리 신청 + 독립리그 신청 */
export declare function selectDraftCandidatesNative(paramsJson: string): string
/** NPC 드래프트 시뮬 */
export declare function runDraftNative(paramsJson: string): string
/** 드래프트 결과 NPC에 적용 */
export declare function applyDraftNative(paramsJson: string): string
/** 배경 고교 졸업생 드래프트 시뮬레이션 */
export declare function bgHsGraduateDraftNative(paramsJson: string): string
/** 주인공 드래프트 결과 결정 */
export declare function determineProtagonistDraftNative(paramsJson: string): string
/** 드래프트 보드 — 전체 픽 시퀀스 사전 계산 */
export declare function runDraftBoardNative(paramsJson: string): string
/** 주인공 학년 진급 */
export declare function advanceProtagonistGradeNative(paramsJson: string): string
/** HS + 대학 전체 학년 진급 (단일 호출) */
export declare function advanceAllGradesNative(paramsJson: string): string
/** 전체 NPC 나이 +1 (학년 진급 이후 단일 호출) */
export declare function advanceAllAgesNative(paramsJson: string): string
/** 주간 훈련 성장 계산 */
export declare function calcTrainingGrowthNative(paramsJson: string): string
/**
 * 훈련 계획 미리보기 — **실제 계산과 같은 `plan_load`를 쓴다.**
 *
 * 훈련 화면이 자기 식으로 예상치를 만들던 시절엔 슬롯 배수(0.5)도 피로 구간
 * 승수(1.5/2.5/4.0)도 몰라서, 화면은 "피로 +7"이라 하고 엔진은 −4.25를
 * 적용했다 — 부호가 반대였다. 화면은 이제 계산하지 않고 묻는다.
 */
export declare function previewTrainingNative(paramsJson: string): string
/**
 * 이번 주 부상 확률 — **`calc_injury`가 굴리는 것과 같은 식이다.**
 * 훈련 화면이 예상 피로로 이걸 물어 "부상위험 N%"를 낸다.
 */
export declare function injuryChanceNative(paramsJson: string): string
/**
 * 폼 무너짐 조회 — **경기에 걸리는 것과 같은 식이다.**
 * 훈련·내 정보 화면이 "제구 −3 · 커맨드 −2"를 이걸로 띄운다.
 */
export declare function formPenaltyNative(paramsJson: string): string
/** 경기 성장 계산 */
export declare function calcGameGrowthNative(paramsJson: string): string
/** 주인공 에이징 (시즌 종료 1회 호출) */
export declare function calcProtagonistAgingNative(paramsJson: string): string
/** 진로 선택 → 다음 스텝 */
export declare function resolveCareerChoiceNative(paramsJson: string): string
/** 고교 투수 포지션 배정 (SP / RP) */
export declare function assignHighschoolPositionNative(paramsJson: string): string
/** 주인공 투수 역할 배정 */
export declare function assignProtagonistRoleNative(paramsJson: string): string
/** 불펜 등판 판정 */
export declare function relieverWouldPitchNative(paramsJson: string): string
/** 시즌 레이팅 계산 */
export declare function calcSeasonRatingNative(paramsJson: string): string
/** 시장 연봉 계산 */
export declare function calcMarketSalaryNative(paramsJson: string): string
/** 제안 연봉 계산 */
export declare function calcOfferedSalaryNative(paramsJson: string): string
/** 주인공 제안 연봉 계산 (시즌 스탯 반영) */
export declare function calcOfferedSalaryForProtagonistNative(paramsJson: string): string
/** NPC 재계약 연봉 계산 */
export declare function calcNpcRenewalSalaryNative(paramsJson: string): string
/** NPC 재계약 기간 계산 */
export declare function calcNpcContractYearsNative(paramsJson: string): string
/** FA 오퍼 생성 */
export declare function generateFaOffersNative(paramsJson: string): string
/** 드래프트 순위/계약금 계산 */
export declare function calcDraftRankNative(paramsJson: string): string
/** 체육부대 후보 30명 공개 (W50 루머) */
export declare function calcSportsUnitCandidatesNative(paramsJson: string): string
/** 체육부대 최종 선발 (W52 입대 신청자 기준) */
export declare function calcSportsUnitSelectionNative(paramsJson: string): string
/** 일반병 입대 대상 랜덤 선택 (시즌당 max_count명 상한) */
export declare function pickGeneralEnlisteesNative(paramsJson: string): string
/** 조기 입대 자발적 선택 결정 (25~27세 주전 경쟁 탈락 KBL 선수) */
export declare function calcEarlyEnlistDecisionsNative(paramsJson: string): string
/** 독립리그 KBL 스카우트 제의 계산 */
export declare function calcIndieScoutOfferNative(paramsJson: string): string
/** 권역 주말리그 — 권역 크기가 달라도 팀당 경기 수를 균등하게 (Phase 5-3) */
export declare function generateRegionalScheduleNative(p: string): string
/** 권역 순위 → 전국대회 참가팀 선발 (권역 크기 비례 배분 + 와일드카드) */
export declare function selectTournamentEntrantsNative(p: string): string
/** 시드 순 참가팀 → 전 라운드 브래킷 뼈대 (부전승 자동 반영) */
export declare function generateTournamentBracketNative(p: string): string
/** 한 라운드 결과 반영 → 다음 라운드 대진 확정 */
export declare function advanceTournamentRoundNative(p: string): string
/** 해당 라운드에서 **실제로 치를** 경기만 일정 형태로 (부전승·미확정 제외) */
export declare function tournamentRoundScheduleNative(p: string): string
/** 프로 2군 축약 포스트시즌 — 상위 4팀 단판 사다리 (Phase 5-7) */
export declare function buildFarmBracketNative(p: string): string
/** 팀 목록 + 생성 규칙 → 스태프 전원 (worldSeed 결정적) */
export declare function generateStaffNative(p: string): string
/** 시즌 종료 → 스태프 나이·경력성장·은퇴·경질·이동 (Phase 6B) */
export declare function advanceStaffSeasonNative(p: string): string
/** 상무 로스터 — 복무 중인 선수 + 계급 + 전역 연도 (원소속은 실재 팀에서 지정) */
export declare function generateMilitaryRosterNative(p: string): string
/** 새 게임 시점의 과거 경력 (입단·이적) — slot.db transactions로 들어간다 */
export declare function generateCareerHistoryNative(p: string): string
/** 새로 만난 사람들의 초기 관계값 (중립 0 + 성향 편차) */
export declare function initRelationsNative(p: string): string
/** 주간 관계 갱신 — contact가 together인 상대만 움직인다 */
export declare function weeklyRelationsNative(p: string): string
/** 시즌 종료 — together는 총평 가산, apart는 감쇠, ended는 동결 */
export declare function seasonRelationsNative(p: string): string
/** 팀 이동 감쇠 (감쇠 후 보존 — 행은 남는다) */
export declare function relationMoveDecayNative(p: string): string
/** 관계 → 실제 판정 보정 (보직 OVR 평가 · 훈련 효율) */
export declare function relationEffectsNative(p: string): string
/** 7단계 라벨 표. TS `types/relationship.ts`의 미러가 어긋났는지 대조하는 데 쓴다 */
export declare function relationLabelTableNative(): string
/** 투구수별 의무 휴식을 채웠는지 (일 단위 — 주 단위로는 주말 연투가 안 걸린다) */
export declare function checkPitcherRestNative(p: string): string
/** 리그별 투구수 상한 (고교 105 / 그 외 120) */
export declare function leaguePitchLimitNative(p: string): string
/** 한 단계 일정 — 생존팀끼리 새 라운드로빈 */
export declare function generateSurvivalStageNative(p: string): string
/** 단계 종료 → 생존팀·탈락팀 판정 */
export declare function survivalCutoffNative(p: string): string
/** 4차 Stage 사다리 — 준PO(단판) → PO(단판) → 챔피언결정전(3전2승) */
export declare function buildIndLadderNative(p: string): string
/** 참가팀 → 조 추첨 + 예선 일정 (worldSeed 결정적) */
export declare function buildGroupStageNative(p: string): string
/** 예선 경기 결과 → 조 순위 반영 */
export declare function applyGroupResultsNative(p: string): string
/** 예선 통과팀 (본선 시드 순) */
export declare function groupStageQualifiersNative(p: string): string
/** 우승팀 (결승 승자 미정이면 null) — 시즌 종료 시상·기록용 */
export declare function tournamentChampionNative(p: string): string
export declare function generateScheduleNative(p: string): string
export declare function generateKblScheduleNative(p: string): string
export declare function generateAblScheduleNative(p: string): string
export declare function generateJblScheduleNative(p: string): string
export declare function generateLeagueScheduleNative(p: string): string
export declare function generateAllLeagueSchedulesNative(p: string): string
export declare function buildKblBracketNative(p: string): string
export declare function buildAblBracketNative(p: string): string
export declare function buildJblBracketNative(p: string): string
export declare function applyGameToSeriesNative(p: string): string
export declare function fillNextSeriesNative(p: string): string
export declare function resolveNonProtagonistSeriesNative(p: string): string
export declare function makeSeriesGameNative(p: string): string
export declare function shuffleAblConferencesNative(p: string): string
export declare function weekCalcFacilityEffNative(p: string): string
export declare function weekCalcInjuryNative(p: string): string
export declare function weekCalcHsAdmissionsNative(p: string): string
export declare function weekCalcTradeRumorNative(p: string): string
export declare function weekCalcExamResultNative(p: string): string
export declare function weekCalcMilitaryNative(p: string): string
export declare function weekCalcNpcFallbackNative(p: string): string
export declare function weekRollRandomBatchNative(count: number): string
export declare function weekCalcNpcInjuriesNative(p: string): string
/** 리그 활성화 시점 로스터 생성 — worldSeed 결정적 (DESIGN.md §8.3) */
export declare function generateLeagueRosterNative(paramsJson: string): string
/**
 * 외국인 교체 영입 — 시즌 종료 후 빈 슬롯만큼 새 용병을 만든다 (F-4).
 * 확장팩(ABL·JBL)이 닫혀 있어도 KBL 외국인 자리가 비지 않게 하는 경로다
 */
export declare function generateForeignPlayersNative(paramsJson: string): string
/** 반경 2(드리프트) 리그 순위표 주간 갱신 — 팀 전력치 + 노이즈로 승패만 누적 (DESIGN.md §2.1) */
export declare function standingsDriftNative(paramsJson: string): string
/** 타 리그 Named NPC 주간 합성 성적 — worldSeed 결정적 (DESIGN.md §4.2, R3b) */
export declare function syntheticWeeklyPerfNative(paramsJson: string): string
export declare function applyScoutingNoiseNative(paramsJson: string): string
export declare function evalCallupCandidatesNative(paramsJson: string): string
export declare function evalCalldownCandidatesNative(paramsJson: string): string
export declare function evalReleasePriorityNative(paramsJson: string): string
export declare function evalFaBidNative(paramsJson: string): string
export declare function evalRenewalOfferNative(paramsJson: string): string
export declare function evalNewContractNative(paramsJson: string): string
export declare function evalRetirementSuggestionNative(paramsJson: string): string
export declare function generateTradeProposalsNative(paramsJson: string): string
export declare function evalTradeValueNative(paramsJson: string): string
export declare function evalMedicalTestNative(paramsJson: string): string
export declare function calcWinNowPressureUpdateNative(paramsJson: string): string
export declare function calcScoutingImprovementNative(paramsJson: string): string
export declare function playerEvalFaDecisionNative(paramsJson: string): string
export declare function playerEvalTradeResponseNative(paramsJson: string): string
export declare function playerEvalContractOfferNative(paramsJson: string): string
export declare function playerEvalRetirementResponseNative(paramsJson: string): string
export declare function playerRankFaOffersNative(paramsJson: string): string
export declare function updatePlayerLoyaltyNative(paramsJson: string): string
