/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 세이브 데이터 HMAC-SHA256 서명 (키는 바이너리 내부) */
export declare function computeSaveSig(snapshot: string): string
/** 세이브 데이터 암호화 → base64(nonce || ciphertext) */
export declare function encryptSaveNative(plaintext: string): string
/** 세이브 데이터 복호화 (구 평문 포맷 자동 감지) */
export declare function decryptSaveNative(ciphertext: string): string
/** 서명 검증 — 일치하면 true */
export declare function verifySaveSig(snapshot: string, sig: string): boolean
/** 초기 경기 상태 생성 */
export declare function startMatchNative(optionsJson: string): string
/** 주인공 인터랙티브 투구 (1구) */
export declare function stepPitchNative(stateJson: string, decisionJson: string): string
/** 경기 종료 처리 */
export declare function finishMatchNative(stateJson: string): string
/** 현재 주인공 투구 차례 여부 */
export declare function isProtagonistPitchingNative(stateJson: string): boolean
/** 다음 게임 페이즈 결정 (orchestrator) */
export declare function advanceGamePhaseNative(stateJson: string): string
/** 등판 트리거 충족 시점까지 자동 시뮬 */
export declare function simUntilEntry(stateJson: string): string
/** 게임 종료까지 자동 시뮬 */
export declare function simToGameEnd(stateJson: string): string
/** 반이닝 자동 시뮬 */
export declare function simHalfInning(stateJson: string): string
/** 감독 자동 마운드 방문 체크 */
export declare function autoMoundVisitNative(stateJson: string): string
/** 마운드 방문 적용 */
export declare function requestMoundVisitNative(stateJson: string): string
/** 주인공 강판 판단 */
export declare function shouldProtagonistExitNative(stateJson: string): string
/** 헤드리스 게임 시뮬 (튜닝 랩용) */
export declare function runSimpleGame(paramsJson: string): string
/** NPC 게임 헤드리스 시뮬 */
export declare function simGameNative(paramsJson: string): string
/** 오프시즌 전체 처리 */
export declare function runOffseasonNative(paramsJson: string): string
/** 고교 학년 진급 */
export declare function advanceGradesNative(paramsJson: string): string
/** NPC 월간 성장/하락 처리 */
export declare function npcCalcMonthlyGrowth(paramsJson: string): string
/** 신입생 벌크 생성 */
export declare function generateFreshmenNative(paramsJson: string): string
/** NPC 드래프트 시뮬 */
export declare function runDraftNative(paramsJson: string): string
/** 드래프트 결과 NPC에 적용 */
export declare function applyDraftNative(paramsJson: string): string
/** 주인공 드래프트 결과 결정 */
export declare function determineProtagonistDraftNative(paramsJson: string): string
/** 주인공 학년 진급 */
export declare function advanceProtagonistGradeNative(paramsJson: string): string
/** 주간 훈련 성장 계산 */
export declare function calcTrainingGrowthNative(paramsJson: string): string
/** 경기 성장 계산 */
export declare function calcGameGrowthNative(paramsJson: string): string
/** 주인공 에이징 (시즌 종료 1회 호출) */
export declare function calcProtagonistAgingNative(paramsJson: string): string
/** 진로 선택 → 다음 스텝 */
export declare function resolveCareerChoiceNative(paramsJson: string): string
/** 고교 투수 포지션 배정 (SP / RP) */
export declare function assignHighschoolPositionNative(paramsJson: string): string
/** 주인공 투수 역할 배정 */
export declare function assignProtagonistRoleNative(paramsJson: string): string
/** 불펜 등판 판정 */
export declare function relieverWouldPitchNative(paramsJson: string): string
/** 시즌 레이팅 계산 */
export declare function calcSeasonRatingNative(paramsJson: string): string
/** 시장 연봉 계산 */
export declare function calcMarketSalaryNative(paramsJson: string): string
/** 제안 연봉 계산 */
export declare function calcOfferedSalaryNative(paramsJson: string): string
/** 주인공 제안 연봉 계산 (시즌 스탯 반영) */
export declare function calcOfferedSalaryForProtagonistNative(paramsJson: string): string
/** FA 오퍼 생성 */
export declare function generateFaOffersNative(paramsJson: string): string
/** 드래프트 순위/계약금 계산 */
export declare function calcDraftRankNative(paramsJson: string): string
export declare function generateScheduleNative(p: string): string
export declare function generateKblScheduleNative(p: string): string
export declare function generateAblScheduleNative(p: string): string
export declare function generateHsScheduleNative(p: string): string
export declare function generateLeagueScheduleNative(p: string): string
export declare function generateAllLeagueSchedulesNative(p: string): string
export declare function generateHsPostseasonSemisNative(p: string): string
export declare function generateHsPostseasonFinalNative(p: string): string
export declare function shuffleHsGroupsNative(p: string): string
export declare function buildKblBracketNative(p: string): string
export declare function buildAblBracketNative(p: string): string
export declare function buildUnivBracketNative(p: string): string
export declare function buildIndBracketNative(p: string): string
export declare function applyGameToSeriesNative(p: string): string
export declare function fillNextSeriesNative(p: string): string
export declare function resolveNonProtagonistSeriesNative(p: string): string
export declare function makeSeriesGameNative(p: string): string
export declare function shuffleAblConferencesNative(p: string): string
export declare function weekCalcFacilityEffNative(p: string): string
export declare function weekCalcWeeklyNetNative(p: string): string
export declare function weekCalcInjuryNative(p: string): string
export declare function weekCalcHsAdmissionsNative(p: string): string
export declare function weekCalcTradeRumorNative(p: string): string
export declare function weekCalcExamResultNative(p: string): string
export declare function weekCalcMilitaryNative(p: string): string
export declare function weekCalcNpcFallbackNative(p: string): string
export declare function weekRollRandomBatchNative(count: number): string
export declare function weekCalcNpcInjuriesNative(p: string): string
