/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'engine-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./engine-native.android-arm64.node')
          } else {
            nativeBinding = require('@projectb/engine-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'engine-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./engine-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('@projectb/engine-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'engine-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./engine-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@projectb/engine-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'engine-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./engine-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@projectb/engine-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'engine-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./engine-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@projectb/engine-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'engine-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./engine-native.darwin-universal.node')
      } else {
        nativeBinding = require('@projectb/engine-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'engine-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./engine-native.darwin-x64.node')
          } else {
            nativeBinding = require('@projectb/engine-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'engine-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./engine-native.darwin-arm64.node')
          } else {
            nativeBinding = require('@projectb/engine-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'engine-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./engine-native.freebsd-x64.node')
      } else {
        nativeBinding = require('@projectb/engine-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'engine-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./engine-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('@projectb/engine-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'engine-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./engine-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@projectb/engine-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'engine-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./engine-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@projectb/engine-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'engine-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./engine-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@projectb/engine-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'engine-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./engine-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@projectb/engine-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'engine-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./engine-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@projectb/engine-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'engine-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./engine-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@projectb/engine-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'engine-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./engine-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@projectb/engine-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'engine-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./engine-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@projectb/engine-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { computeSaveSig, verifySaveSig, startMatchNative, stepPitchNative, finishMatchNative, isProtagonistPitchingNative, advanceGamePhaseNative, simUntilEntry, simToGameEnd, simHalfInning, autoMoundVisitNative, requestMoundVisitNative, shouldProtagonistExitNative, runSimpleGame, simGameNative, runOffseasonNative, advanceGradesNative, generateFreshmenNative, runDraftNative, applyDraftNative, determineProtagonistDraftNative, advanceProtagonistGradeNative } = nativeBinding

module.exports.computeSaveSig = computeSaveSig
module.exports.verifySaveSig = verifySaveSig
module.exports.startMatchNative = startMatchNative
module.exports.stepPitchNative = stepPitchNative
module.exports.finishMatchNative = finishMatchNative
module.exports.isProtagonistPitchingNative = isProtagonistPitchingNative
module.exports.advanceGamePhaseNative = advanceGamePhaseNative
module.exports.simUntilEntry = simUntilEntry
module.exports.simToGameEnd = simToGameEnd
module.exports.simHalfInning = simHalfInning
module.exports.autoMoundVisitNative = autoMoundVisitNative
module.exports.requestMoundVisitNative = requestMoundVisitNative
module.exports.shouldProtagonistExitNative = shouldProtagonistExitNative
module.exports.runSimpleGame = runSimpleGame
module.exports.simGameNative = simGameNative
module.exports.runOffseasonNative = runOffseasonNative
module.exports.advanceGradesNative = advanceGradesNative
module.exports.generateFreshmenNative = generateFreshmenNative
module.exports.runDraftNative = runDraftNative
module.exports.applyDraftNative = applyDraftNative
module.exports.determineProtagonistDraftNative = determineProtagonistDraftNative
module.exports.advanceProtagonistGradeNative = advanceProtagonistGradeNative
