// 이 파일은 생성물이다 — 직접 편집하지 말 것.
// 생성: python scripts/build_refs_from_seeds.py
// 정본: resource/data/seeds/onepitch/*.csv → resource/data/master/entities/refs.json
//
// 국내 182팀 (고교 102 · 대학 50 · 독립 10 · 프로 1군 10 · 2군 10)

export const HS_ALL_TEAMS: string[] = [
  "TEAM_HS_AEWOL",
  "TEAM_HS_BAEGYANG",
  "TEAM_HS_BAEKHO",
  "TEAM_HS_BAEKSEOK",
  "TEAM_HS_BITGOEUL",
  "TEAM_HS_BONGUII",
  "TEAM_HS_BUGAK",
  "TEAM_HS_BULMO",
  "TEAM_HS_BUNDANG",
  "TEAM_HS_BUNSEONG",
  "TEAM_HS_CHEONGNA",
  "TEAM_HS_CHEONGRAM",
  "TEAM_HS_CHEONGUN",
  "TEAM_HS_CHIAK",
  "TEAM_HS_CHOKSEOK",
  "TEAM_HS_DAEYANG",
  "TEAM_HS_DALSEONG",
  "TEAM_HS_DONGNAE",
  "TEAM_HS_DOSEONG",
  "TEAM_HS_EUNPYEONG",
  "TEAM_HS_GANGBYEON",
  "TEAM_HS_GANGJIN",
  "TEAM_HS_GARAK",
  "TEAM_HS_GAYA",
  "TEAM_HS_GEOJE",
  "TEAM_HS_GEUMGANG",
  "TEAM_HS_GEUMJEONG",
  "TEAM_HS_GEUMO",
  "TEAM_HS_GEUMSAN",
  "TEAM_HS_GIHEUNG",
  "TEAM_HS_GIMPO",
  "TEAM_HS_GWANGAN",
  "TEAM_HS_GWANGGYO",
  "TEAM_HS_GWANGUN",
  "TEAM_HS_GYEBAEK",
  "TEAM_HS_GYEONGPO",
  "TEAM_HS_GYERIM",
  "TEAM_HS_GYERYONG",
  "TEAM_HS_GYEYANG",
  "TEAM_HS_HAEUN",
  "TEAM_HS_HAHOE",
  "TEAM_HS_HALLA",
  "TEAM_HS_HANBIT",
  "TEAM_HS_HANNAE",
  "TEAM_HS_HANSEONG",
  "TEAM_HS_HONGJU",
  "TEAM_HS_HWASUN",
  "TEAM_HS_HYEONGSAN",
  "TEAM_HS_ILSAN",
  "TEAM_HS_JUNGNIM",
  "TEAM_HS_JUNGNYEONG",
  "TEAM_HS_JUNGWON",
  "TEAM_HS_MANWOL",
  "TEAM_HS_MASANMAN",
  "TEAM_HS_MISA",
  "TEAM_HS_MONGNYEON",
  "TEAM_HS_MUDEUNG",
  "TEAM_HS_MUJIN",
  "TEAM_HS_MUNSU",
  "TEAM_HS_MUSIM",
  "TEAM_HS_MYEONGIL",
  "TEAM_HS_NAKDONG",
  "TEAM_HS_NAMAK",
  "TEAM_HS_NAMGANG",
  "TEAM_HS_NAMSAN",
  "TEAM_HS_ODONG",
  "TEAM_HS_OREUM",
  "TEAM_HS_OSAN",
  "TEAM_HS_PALDAL",
  "TEAM_HS_PALGONG",
  "TEAM_HS_PANGYO",
  "TEAM_HS_PUNGNAM",
  "TEAM_HS_PYEONGCHON",
  "TEAM_HS_PYEONGTAEK",
  "TEAM_HS_SAMJEON",
  "TEAM_HS_SANGDANG",
  "TEAM_HS_SANGNOK",
  "TEAM_HS_SEOGWI",
  "TEAM_HS_SEOLBONG",
  "TEAM_HS_SEONGGEO",
  "TEAM_HS_SEONGSAN",
  "TEAM_HS_SEORAK",
  "TEAM_HS_SEUNGJU",
  "TEAM_HS_SIHWA",
  "TEAM_HS_SINCHEON",
  "TEAM_HS_SINJEONG",
  "TEAM_HS_SONGRIM",
  "TEAM_HS_SUSEONG",
  "TEAM_HS_TAEBAEK",
  "TEAM_HS_TAEHWA",
  "TEAM_HS_TAEJONG",
  "TEAM_HS_TANGEUM",
  "TEAM_HS_TONGYEONG",
  "TEAM_HS_WANSAN",
  "TEAM_HS_WOLMYEONG",
  "TEAM_HS_YANGCHEON",
  "TEAM_HS_YEONGIL",
  "TEAM_HS_YEONGNAM",
  "TEAM_HS_YEONSU",
  "TEAM_HS_YESAN",
  "TEAM_HS_YUDAL",
  "TEAM_HS_YUSEONG",
];

export const HS_SELECTABLE_TEAMS: string[] = [
  "TEAM_HS_AEWOL",
  "TEAM_HS_BAEGYANG",
  "TEAM_HS_BAEKHO",
  "TEAM_HS_BAEKSEOK",
  "TEAM_HS_BITGOEUL",
  "TEAM_HS_BONGUII",
  "TEAM_HS_BUGAK",
  "TEAM_HS_BULMO",
  "TEAM_HS_BUNDANG",
  "TEAM_HS_BUNSEONG",
  "TEAM_HS_CHEONGNA",
  "TEAM_HS_CHEONGRAM",
  "TEAM_HS_CHEONGUN",
  "TEAM_HS_CHIAK",
  "TEAM_HS_CHOKSEOK",
  "TEAM_HS_DAEYANG",
  "TEAM_HS_DALSEONG",
  "TEAM_HS_DONGNAE",
  "TEAM_HS_DOSEONG",
  "TEAM_HS_EUNPYEONG",
  "TEAM_HS_GANGBYEON",
  "TEAM_HS_GANGJIN",
  "TEAM_HS_GARAK",
  "TEAM_HS_GAYA",
  "TEAM_HS_GEOJE",
  "TEAM_HS_GEUMGANG",
  "TEAM_HS_GEUMJEONG",
  "TEAM_HS_GEUMO",
  "TEAM_HS_GEUMSAN",
  "TEAM_HS_GIHEUNG",
  "TEAM_HS_GIMPO",
  "TEAM_HS_GWANGAN",
  "TEAM_HS_GWANGGYO",
  "TEAM_HS_GWANGUN",
  "TEAM_HS_GYEBAEK",
  "TEAM_HS_GYEONGPO",
  "TEAM_HS_GYERIM",
  "TEAM_HS_GYERYONG",
  "TEAM_HS_GYEYANG",
  "TEAM_HS_HAEUN",
  "TEAM_HS_HAHOE",
  "TEAM_HS_HALLA",
  "TEAM_HS_HANBIT",
  "TEAM_HS_HANNAE",
  "TEAM_HS_HANSEONG",
  "TEAM_HS_HONGJU",
  "TEAM_HS_HWASUN",
  "TEAM_HS_HYEONGSAN",
  "TEAM_HS_ILSAN",
  "TEAM_HS_JUNGNIM",
  "TEAM_HS_JUNGNYEONG",
  "TEAM_HS_JUNGWON",
  "TEAM_HS_MANWOL",
  "TEAM_HS_MASANMAN",
  "TEAM_HS_MISA",
  "TEAM_HS_MONGNYEON",
  "TEAM_HS_MUDEUNG",
  "TEAM_HS_MUJIN",
  "TEAM_HS_MUNSU",
  "TEAM_HS_MUSIM",
  "TEAM_HS_MYEONGIL",
  "TEAM_HS_NAKDONG",
  "TEAM_HS_NAMAK",
  "TEAM_HS_NAMGANG",
  "TEAM_HS_NAMSAN",
  "TEAM_HS_ODONG",
  "TEAM_HS_OREUM",
  "TEAM_HS_OSAN",
  "TEAM_HS_PALDAL",
  "TEAM_HS_PALGONG",
  "TEAM_HS_PANGYO",
  "TEAM_HS_PUNGNAM",
  "TEAM_HS_PYEONGCHON",
  "TEAM_HS_PYEONGTAEK",
  "TEAM_HS_SAMJEON",
  "TEAM_HS_SANGDANG",
  "TEAM_HS_SANGNOK",
  "TEAM_HS_SEOGWI",
  "TEAM_HS_SEOLBONG",
  "TEAM_HS_SEONGGEO",
  "TEAM_HS_SEONGSAN",
  "TEAM_HS_SEORAK",
  "TEAM_HS_SEUNGJU",
  "TEAM_HS_SIHWA",
  "TEAM_HS_SINCHEON",
  "TEAM_HS_SINJEONG",
  "TEAM_HS_SONGRIM",
  "TEAM_HS_SUSEONG",
  "TEAM_HS_TAEBAEK",
  "TEAM_HS_TAEHWA",
  "TEAM_HS_TAEJONG",
  "TEAM_HS_TANGEUM",
  "TEAM_HS_TONGYEONG",
  "TEAM_HS_WANSAN",
  "TEAM_HS_WOLMYEONG",
  "TEAM_HS_YANGCHEON",
  "TEAM_HS_YEONGIL",
  "TEAM_HS_YEONGNAM",
  "TEAM_HS_YEONSU",
  "TEAM_HS_YESAN",
  "TEAM_HS_YUDAL",
  "TEAM_HS_YUSEONG",
];

export const UNIV_TEAMS: string[] = [
  "TEAM_UNIV_ASAN",
  "TEAM_UNIV_BAEKJE",
  "TEAM_UNIV_BAEKSAN",
  "TEAM_UNIV_BANWOL",
  "TEAM_UNIV_BISEUL",
  "TEAM_UNIV_BITGOEUL",
  "TEAM_UNIV_BUKHANSAN",
  "TEAM_UNIV_BUNSEONG",
  "TEAM_UNIV_BYEOLLAE",
  "TEAM_UNIV_CHIAK",
  "TEAM_UNIV_DALGUBEOL",
  "TEAM_UNIV_GEOJE",
  "TEAM_UNIV_GEUMJEONG",
  "TEAM_UNIV_GWANAK",
  "TEAM_UNIV_GWANGGYO",
  "TEAM_UNIV_GWANYANG",
  "TEAM_UNIV_GYEONGIN",
  "TEAM_UNIV_GYERYONG",
  "TEAM_UNIV_HAEDONG",
  "TEAM_UNIV_HAHOE",
  "TEAM_UNIV_HALLYU",
  "TEAM_UNIV_HANAM",
  "TEAM_UNIV_HANGANG",
  "TEAM_UNIV_HWAHONG",
  "TEAM_UNIV_HYEONGSAN",
  "TEAM_UNIV_JINWI",
  "TEAM_UNIV_NAMAK",
  "TEAM_UNIV_NAMGANG",
  "TEAM_UNIV_NAMSAN",
  "TEAM_UNIV_ODONG",
  "TEAM_UNIV_OKCHEON",
  "TEAM_UNIV_OSAN",
  "TEAM_UNIV_SANGDANG",
  "TEAM_UNIV_SEOGWI",
  "TEAM_UNIV_SEONGHWAN",
  "TEAM_UNIV_SEORAK",
  "TEAM_UNIV_SEOSAN",
  "TEAM_UNIV_SEOSEOK",
  "TEAM_UNIV_SEUNGJU",
  "TEAM_UNIV_SIHWA",
  "TEAM_UNIV_SONGDO",
  "TEAM_UNIV_SOSA",
  "TEAM_UNIV_SURI",
  "TEAM_UNIV_TAEHWA",
  "TEAM_UNIV_TONGYEONG",
  "TEAM_UNIV_WANSAN",
  "TEAM_UNIV_WOLMI",
  "TEAM_UNIV_YEONGCHEON",
  "TEAM_UNIV_YUDAL",
  "TEAM_UNIV_YUSEONG",
];

export const IND_TEAMS: string[] = [
  "TEAM_IND_BUSAN_SEALIONS",
  "TEAM_IND_DAEGU_HAWKS",
  "TEAM_IND_DAEJEON_BLAZE",
  "TEAM_IND_GWANGJU_RHINOS",
  "TEAM_IND_INCHEON_GRIFFONS",
  "TEAM_IND_PAJU_UNICORNS",
  "TEAM_IND_SANGMU_PHOENIX",
  "TEAM_IND_SEOUL_COMETS",
  "TEAM_IND_SEOUL_RAVENS",
  "TEAM_IND_WONJU_WINNERS",
];

export const KBL_TEAMS: string[] = [
  "TEAM_KBL_BUSAN_WAVES_1",
  "TEAM_KBL_CHANGWON_STARS_1",
  "TEAM_KBL_DAEGU_SABERS_1",
  "TEAM_KBL_DAEJEON_PHANTOMS_1",
  "TEAM_KBL_GWANGJU_PANTHERS_1",
  "TEAM_KBL_INCHEON_SHARKS_1",
  "TEAM_KBL_SEOUL_COBRAS_1",
  "TEAM_KBL_SEOUL_GUARDIANS_1",
  "TEAM_KBL_SEOUL_ROYALS_1",
  "TEAM_KBL_SUWON_KNIGHTS_1",
];

export const KBL_FARM_TEAMS: string[] = [
  "TEAM_KBL_BUSAN_WAVES_2",
  "TEAM_KBL_CHANGWON_STARS_2",
  "TEAM_KBL_DAEGU_SABERS_2",
  "TEAM_KBL_DAEJEON_PHANTOMS_2",
  "TEAM_KBL_GWANGJU_PANTHERS_2",
  "TEAM_KBL_INCHEON_SHARKS_2",
  "TEAM_KBL_SEOUL_COBRAS_2",
  "TEAM_KBL_SEOUL_GUARDIANS_2",
  "TEAM_KBL_SEOUL_ROYALS_2",
  "TEAM_KBL_SUWON_KNIGHTS_2",
];

export const ABL_TEAMS: string[] = [
  "TEAM_ABL_BAYSEALS_1",
  "TEAM_ABL_COASTALRAYS_1",
  "TEAM_ABL_DESERTSERPENTS_1",
  "TEAM_ABL_EMPIRE_1",
  "TEAM_ABL_HARBORHAWKS_1",
  "TEAM_ABL_LAKESPIRITS_1",
  "TEAM_ABL_LONESTARS_1",
  "TEAM_ABL_MOTORWOLVES_1",
  "TEAM_ABL_MOUNTAINPEAKS_1",
  "TEAM_ABL_PEACHTREEFALCONS_1",
  "TEAM_ABL_RAINARROWS_1",
  "TEAM_ABL_RIVERCARDINALS_1",
  "TEAM_ABL_SPACECOMETS_1",
  "TEAM_ABL_SUNDRAGONS_1",
  "TEAM_ABL_WAVERIDERS_1",
  "TEAM_ABL_WINDBEARS_1",
];

export const ABL_FARM_TEAMS: string[] = [
  "TEAM_ABL_BAYSEALS_2",
  "TEAM_ABL_COASTALRAYS_2",
  "TEAM_ABL_DESERTSERPENTS_2",
  "TEAM_ABL_EMPIRE_2",
  "TEAM_ABL_HARBORHAWKS_2",
  "TEAM_ABL_LAKESPIRITS_2",
  "TEAM_ABL_LONESTARS_2",
  "TEAM_ABL_MOTORWOLVES_2",
  "TEAM_ABL_MOUNTAINPEAKS_2",
  "TEAM_ABL_PEACHTREEFALCONS_2",
  "TEAM_ABL_RAINARROWS_2",
  "TEAM_ABL_RIVERCARDINALS_2",
  "TEAM_ABL_SPACECOMETS_2",
  "TEAM_ABL_SUNDRAGONS_2",
  "TEAM_ABL_WAVERIDERS_2",
  "TEAM_ABL_WINDBEARS_2",
];

export const JBL_TEAMS: string[] = [
  "TEAM_JBL_CL_IRONDRAKES_1",
  "TEAM_JBL_CL_IRONSTORMS_1",
  "TEAM_JBL_CL_NEONCRANES_1",
  "TEAM_JBL_CL_SILVERWOLVES_1",
  "TEAM_JBL_CL_TEMPOSTINGS_1",
  "TEAM_JBL_CL_TIDERAVES_1",
  "TEAM_JBL_PL_MARINESOLDIERS_1",
  "TEAM_JBL_PL_POLARBEARS_1",
  "TEAM_JBL_PL_SEAGULLS_1",
  "TEAM_JBL_PL_SPIRITBUFFALOS_1",
  "TEAM_JBL_PL_SUNS_1",
  "TEAM_JBL_PL_THUNDERFALCONS_1",
];

export const JBL_FARM_TEAMS: string[] = [
  "TEAM_JBL_CL_IRONDRAKES_2",
  "TEAM_JBL_CL_IRONSTORMS_2",
  "TEAM_JBL_CL_NEONCRANES_2",
  "TEAM_JBL_CL_SILVERWOLVES_2",
  "TEAM_JBL_CL_TEMPOSTINGS_2",
  "TEAM_JBL_CL_TIDERAVES_2",
  "TEAM_JBL_PL_MARINESOLDIERS_2",
  "TEAM_JBL_PL_POLARBEARS_2",
  "TEAM_JBL_PL_SEAGULLS_2",
  "TEAM_JBL_PL_SPIRITBUFFALOS_2",
  "TEAM_JBL_PL_SUNS_2",
  "TEAM_JBL_PL_THUNDERFALCONS_2",
];

/** 고교 8권역 — 거점구장 공유 그룹. 5-3 주말리그 편성의 기준 */
export const HS_REGIONS: Record<string, string[]> = {
  "STADIUM_GYERYONG": [
    "TEAM_HS_BAEKSEOK",
    "TEAM_HS_GEUMGANG",
    "TEAM_HS_GEUMSAN",
    "TEAM_HS_GYEBAEK",
    "TEAM_HS_GYERYONG",
    "TEAM_HS_HONGJU",
    "TEAM_HS_MUSIM",
    "TEAM_HS_SANGDANG",
    "TEAM_HS_SEONGGEO",
    "TEAM_HS_TANGEUM",
    "TEAM_HS_YESAN",
    "TEAM_HS_YUSEONG",
  ],
  "STADIUM_HALLA": [
    "TEAM_HS_AEWOL",
    "TEAM_HS_HALLA",
    "TEAM_HS_HANNAE",
    "TEAM_HS_OREUM",
    "TEAM_HS_SEOGWI",
    "TEAM_HS_SEONGSAN",
  ],
  "STADIUM_HANGANG": [
    "TEAM_HS_BUGAK",
    "TEAM_HS_CHEONGRAM",
    "TEAM_HS_CHEONGUN",
    "TEAM_HS_DAEYANG",
    "TEAM_HS_DOSEONG",
    "TEAM_HS_EUNPYEONG",
    "TEAM_HS_GANGBYEON",
    "TEAM_HS_GWANGUN",
    "TEAM_HS_HANBIT",
    "TEAM_HS_HANSEONG",
    "TEAM_HS_MONGNYEON",
    "TEAM_HS_MYEONGIL",
    "TEAM_HS_NAMSAN",
    "TEAM_HS_SAMJEON",
    "TEAM_HS_SINJEONG",
    "TEAM_HS_YANGCHEON",
  ],
  "STADIUM_MUJIGAE": [
    "TEAM_HS_BAEKHO",
    "TEAM_HS_BUNDANG",
    "TEAM_HS_CHEONGNA",
    "TEAM_HS_GIHEUNG",
    "TEAM_HS_GIMPO",
    "TEAM_HS_GWANGGYO",
    "TEAM_HS_GYEYANG",
    "TEAM_HS_ILSAN",
    "TEAM_HS_JUNGWON",
    "TEAM_HS_MANWOL",
    "TEAM_HS_MISA",
    "TEAM_HS_OSAN",
    "TEAM_HS_PANGYO",
    "TEAM_HS_PYEONGCHON",
    "TEAM_HS_PYEONGTAEK",
    "TEAM_HS_SANGNOK",
    "TEAM_HS_SIHWA",
    "TEAM_HS_SONGRIM",
    "TEAM_HS_SUSEONG",
    "TEAM_HS_YEONSU",
  ],
  "STADIUM_NAKDONG": [
    "TEAM_HS_BULMO",
    "TEAM_HS_BUNSEONG",
    "TEAM_HS_CHOKSEOK",
    "TEAM_HS_DONGNAE",
    "TEAM_HS_GARAK",
    "TEAM_HS_GAYA",
    "TEAM_HS_GEOJE",
    "TEAM_HS_GEUMJEONG",
    "TEAM_HS_GWANGAN",
    "TEAM_HS_HAEUN",
    "TEAM_HS_MASANMAN",
    "TEAM_HS_MUNSU",
    "TEAM_HS_NAMGANG",
    "TEAM_HS_TAEHWA",
    "TEAM_HS_TAEJONG",
    "TEAM_HS_TONGYEONG",
  ],
  "STADIUM_PALGONG": [
    "TEAM_HS_DALSEONG",
    "TEAM_HS_GEUMO",
    "TEAM_HS_GYERIM",
    "TEAM_HS_HAHOE",
    "TEAM_HS_HYEONGSAN",
    "TEAM_HS_JUNGNYEONG",
    "TEAM_HS_NAKDONG",
    "TEAM_HS_PALDAL",
    "TEAM_HS_PALGONG",
    "TEAM_HS_SINCHEON",
    "TEAM_HS_YEONGIL",
    "TEAM_HS_YEONGNAM",
  ],
  "STADIUM_SEORAK_HS": [
    "TEAM_HS_BONGUII",
    "TEAM_HS_CHIAK",
    "TEAM_HS_GYEONGPO",
    "TEAM_HS_SEOLBONG",
    "TEAM_HS_SEORAK",
    "TEAM_HS_TAEBAEK",
  ],
  "STADIUM_YEONGSAN": [
    "TEAM_HS_BAEGYANG",
    "TEAM_HS_BITGOEUL",
    "TEAM_HS_GANGJIN",
    "TEAM_HS_HWASUN",
    "TEAM_HS_JUNGNIM",
    "TEAM_HS_MUDEUNG",
    "TEAM_HS_MUJIN",
    "TEAM_HS_NAMAK",
    "TEAM_HS_ODONG",
    "TEAM_HS_PUNGNAM",
    "TEAM_HS_SEUNGJU",
    "TEAM_HS_WANSAN",
    "TEAM_HS_WOLMYEONG",
    "TEAM_HS_YUDAL",
  ],
};

/** 대학 5조(A~E) — 거점구장 공유 그룹. 고교 권역과 같은 규칙 */
export const UNIV_GROUPS: Record<string, string[]> = {
  "STADIUM_BYEOLBIT": [
    "TEAM_UNIV_BANWOL",
    "TEAM_UNIV_BYEOLLAE",
    "TEAM_UNIV_GWANGGYO",
    "TEAM_UNIV_GWANYANG",
    "TEAM_UNIV_HANAM",
    "TEAM_UNIV_JINWI",
    "TEAM_UNIV_OSAN",
    "TEAM_UNIV_SIHWA",
    "TEAM_UNIV_SOSA",
    "TEAM_UNIV_WOLMI",
  ],
  "STADIUM_GEUMGANG_UNIV": [
    "TEAM_UNIV_ASAN",
    "TEAM_UNIV_BAEKJE",
    "TEAM_UNIV_CHIAK",
    "TEAM_UNIV_GYERYONG",
    "TEAM_UNIV_OKCHEON",
    "TEAM_UNIV_SANGDANG",
    "TEAM_UNIV_SEONGHWAN",
    "TEAM_UNIV_SEORAK",
    "TEAM_UNIV_SEOSAN",
    "TEAM_UNIV_YUSEONG",
  ],
  "STADIUM_MIREU": [
    "TEAM_UNIV_BAEKSAN",
    "TEAM_UNIV_BUKHANSAN",
    "TEAM_UNIV_GWANAK",
    "TEAM_UNIV_GYEONGIN",
    "TEAM_UNIV_HALLYU",
    "TEAM_UNIV_HANGANG",
    "TEAM_UNIV_HWAHONG",
    "TEAM_UNIV_NAMSAN",
    "TEAM_UNIV_SONGDO",
    "TEAM_UNIV_SURI",
  ],
  "STADIUM_NOEUL": [
    "TEAM_UNIV_BISEUL",
    "TEAM_UNIV_BITGOEUL",
    "TEAM_UNIV_DALGUBEOL",
    "TEAM_UNIV_HYEONGSAN",
    "TEAM_UNIV_NAMAK",
    "TEAM_UNIV_ODONG",
    "TEAM_UNIV_SEOSEOK",
    "TEAM_UNIV_SEUNGJU",
    "TEAM_UNIV_WANSAN",
    "TEAM_UNIV_YUDAL",
  ],
  "STADIUM_TAEJONG": [
    "TEAM_UNIV_BUNSEONG",
    "TEAM_UNIV_GEOJE",
    "TEAM_UNIV_GEUMJEONG",
    "TEAM_UNIV_HAEDONG",
    "TEAM_UNIV_HAHOE",
    "TEAM_UNIV_NAMGANG",
    "TEAM_UNIV_SEOGWI",
    "TEAM_UNIV_TAEHWA",
    "TEAM_UNIV_TONGYEONG",
    "TEAM_UNIV_YEONGCHEON",
  ],
};

/** 리그 → 조 편성. 대회 참가팀 선발이 이걸로 권역/조를 찾는다 */
export const GROUPS_BY_LEAGUE: Record<string, Record<string, string[]>> = {
  LEAGUE_HIGHSCHOOL: HS_REGIONS,
  LEAGUE_UNIVERSITY: UNIV_GROUPS,
};

export interface LeagueGroupMeta {
  leagueId: string; stadiumId: string; label: string;
  /** 주 안의 날짜 오프셋. 고교 주말리그의 6·7과 같은 축 */
  dayOffsets: number[];
  note: string;
}

/** 조별 요일 패턴. 정본: seeds/onepitch/league_groups.csv */
export const LEAGUE_GROUP_META: LeagueGroupMeta[] = [
  { leagueId: "LEAGUE_UNIVERSITY", stadiumId: "STADIUM_MIREU", label: "A", dayOffsets: [1, 2, 3, 4], note: "화수목금 격주 (서울6+경인4)" },
  { leagueId: "LEAGUE_UNIVERSITY", stadiumId: "STADIUM_BYEOLBIT", label: "B", dayOffsets: [1, 2, 3, 4], note: "화수목금 격주 (경인10)" },
  { leagueId: "LEAGUE_UNIVERSITY", stadiumId: "STADIUM_GEUMGANG_UNIV", label: "C", dayOffsets: [3, 4], note: "매주 목금 (충청8+강원2)" },
  { leagueId: "LEAGUE_UNIVERSITY", stadiumId: "STADIUM_NOEUL", label: "D", dayOffsets: [3, 4], note: "매주 목금 (호남7+대경3)" },
  { leagueId: "LEAGUE_UNIVERSITY", stadiumId: "STADIUM_TAEJONG", label: "E", dayOffsets: [3, 4, 1, 2], note: "기획서는 4월 목금·5월 화수 — 라운드 순환으로 근사 (부경울7+대경2+제주1)" },
];

/** 대회 시드 산출 기준 */
export type TournamentSeedSource =
  | "prev_season"  /* 전년 권역 순위 */
  | "first_half"   /* 전반기 권역 순위 */
  | "second_half"  /* 후반기 권역 순위 */
  | "open";        /* 전원 참가 */

export interface TournamentDef {
  id: string; leagueId: string; name: string; flower: string;
  startWeek: number; endWeek: number;
  totalSlots: number; wildcardSlots: number;
  seedSource: TournamentSeedSource;
  /** 조당 자동 진출 수 고정 (대학 왕중왕전 = 조 1위만). null이면 조 크기 비례 배분 */
  perGroupSlots: number | null;
  /** WC 후보를 조 상위 몇 위까지로 제한 (왕중왕전 = 조 2위까지). null이면 제한 없음 */
  wildcardMaxGroupRank: number | null;
  /** 자동 진출팀을 WC보다 항상 상위 시드로 (왕중왕전) */
  autoSeedsFirst: boolean;
  order: number;
}

/** 대회 카탈로그 (고교 5종 · 대학). 정본: seeds/onepitch/tournaments.csv */
export const TOURNAMENTS: TournamentDef[] = [
  { id: "TOUR_HS_GAENARI", leagueId: "LEAGUE_HIGHSCHOOL", name: "개나리기", flower: "개나리", startWeek: 2, endWeek: 3, totalSlots: 32, wildcardSlots: 8, seedSource: "prev_season", perGroupSlots: null, wildcardMaxGroupRank: null, autoSeedsFirst: false, order: 1 },
  { id: "TOUR_HS_JANGMI", leagueId: "LEAGUE_HIGHSCHOOL", name: "장미기", flower: "장미", startWeek: 14, endWeek: 15, totalSlots: 32, wildcardSlots: 8, seedSource: "first_half", perGroupSlots: null, wildcardMaxGroupRank: null, autoSeedsFirst: false, order: 2 },
  { id: "TOUR_HS_MUGUNGHWA", leagueId: "LEAGUE_HIGHSCHOOL", name: "무궁화기", flower: "무궁화", startWeek: 20, endWeek: 22, totalSlots: 48, wildcardSlots: 12, seedSource: "first_half", perGroupSlots: null, wildcardMaxGroupRank: null, autoSeedsFirst: false, order: 3 },
  { id: "TOUR_HS_GUKHWA", leagueId: "LEAGUE_HIGHSCHOOL", name: "국화기", flower: "국화", startWeek: 31, endWeek: 34, totalSlots: 102, wildcardSlots: 0, seedSource: "open", perGroupSlots: null, wildcardMaxGroupRank: null, autoSeedsFirst: false, order: 4 },
  { id: "TOUR_HS_PAEWANG", leagueId: "LEAGUE_HIGHSCHOOL", name: "패왕기", flower: "왕중왕", startWeek: 40, endWeek: 41, totalSlots: 24, wildcardSlots: 0, seedSource: "second_half", perGroupSlots: null, wildcardMaxGroupRank: null, autoSeedsFirst: false, order: 5 },
  { id: "TOUR_UNIV_WANGJUNGWANG", leagueId: "LEAGUE_UNIVERSITY", name: "왕중왕전", flower: "왕중왕", startWeek: 11, endWeek: 12, totalSlots: 8, wildcardSlots: 3, seedSource: "first_half", perGroupSlots: 1, wildcardMaxGroupRank: 2, autoSeedsFirst: true, order: 1 },
];
