// market은 대부분 주인공 전용(06_시장_계약)이라 I6로 이월(§6-11) — 계속 진행 예정.
pub mod academics;
pub mod career;
pub mod eval;
pub mod event;
pub mod growth;
pub mod injury;
pub mod manager;
pub mod market;
pub mod npc;
pub mod pitch;
pub mod protagonist;
pub mod retirement;
pub mod roster;
pub mod staff;
pub mod training;
pub mod schedule;
pub mod tournament;
#[path = "match_.rs"]
pub mod match_sim;