// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'game.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `with_state_mut`, `with_state`, `world_seed`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GameState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// 뉴게임 — [07_주인공_생성](../../../02_기획/07_주인공_생성.md) §1의 7단계
/// 흐름 중 실제 데이터를 만드는 마지막 단계(스텝 1~6은 Dart 쪽 폼 상태일
/// 뿐 엔진 호출이 아님). 결정적 seed로 배경 세계(172팀 로스터+일정)를
/// 먼저 만든 뒤 주인공을 생성해 전역 세션에 올린다.
Future<void> newGame({
  required String contentDbPath,
  required PlatformInt64 canonicalSeed,
  required String name,
  required String handedness,
  required String schoolTeamId,
  required String archetype,
  String? secondPitch,
}) => RustLib.instance.api.crateApiGameNewGame(
  contentDbPath: contentDbPath,
  canonicalSeed: canonicalSeed,
  name: name,
  handedness: handedness,
  schoolTeamId: schoolTeamId,
  archetype: archetype,
  secondPitch: secondPitch,
);

/// 진행(Continue) — [04_게임루프](../../../03_설계/04_게임루프.md) §2
/// `advance()`를 그대로 노출. 정지점(새 PendingAction 또는 주인공 경기)
/// 까지 하루씩 전진한 뒤 대기 목록을 반환한다.
Future<List<PendingActionInfo>> advance() =>
    RustLib.instance.api.crateApiGameAdvance();

/// PendingAction 응답 — 타입별 `choice_id` 형식은
/// [04_게임루프](../../../03_설계/04_게임루프.md) §3·엔진 `resolve_choice`
/// 문서 참고(`game`: 모드 문자열, `pitch`: `"구종:코스"`, `injuryTreatment`:
/// 치료법, `contractNego`: `"accept:team_id"`/`"counter:team_id:금액"`/
/// `"reject"`, `tradeDecision`: `"accept"`/`"reject"`). 결과가 `Some`이면
/// 매치가 계속 진행 중이라는 뜻 — Dart는 `AwaitingPitch`면 다음 1구를
/// 위해 다시 이 함수를 호출하고, `GameOver`면 경기 요약으로 넘어간다.
Future<MatchStepInfo?> resolveChoice({
  required String actionId,
  required String choiceId,
}) => RustLib.instance.api.crateApiGameResolveChoice(
  actionId: actionId,
  choiceId: choiceId,
);

Future<ProtagonistStatusInfo> getProtagonistStatus() =>
    RustLib.instance.api.crateApiGameGetProtagonistStatus();

/// 지금 세션의 미해결 PendingAction 전체 — 화면 재진입(예: 매치 중 다른
/// 탭 갔다가 복귀) 시 재조회용. `advance`/`resolve_choice`가 반환하는
/// 목록과 항상 같은 소스(`pending_actions` 테이블)를 본다.
Future<List<PendingActionInfo>> getPendingActions() =>
    RustLib.instance.api.crateApiGameGetPendingActions();

Future<MetaStatusInfo> getMetaStatus() =>
    RustLib.instance.api.crateApiGameGetMetaStatus();

/// 1구 조작 집중뷰의 3×3 코스 그리드 버튼 이름 — `sim::pitch::Course`의
/// 9개 값 그대로(`resolve_choice`의 `"구종:코스"` choice_id에 이 이름을
/// 그대로 넣으면 된다). 순수 계산(I/O·락 없음)이라 동기 호출로 둔다 —
/// Dart 쪽에서 `FutureBuilder` 없이 바로 리스트를 쓸 수 있다.
List<String> courseNames() => RustLib.instance.api.crateApiGameCourseNames();

List<TreatmentOption> treatmentOptions({required String severity}) =>
    RustLib.instance.api.crateApiGameTreatmentOptions(severity: severity);

Future<List<TeamOption>> listHsTeams({required String contentDbPath}) =>
    RustLib.instance.api.crateApiGameListHsTeams(contentDbPath: contentDbPath);

/// 지금 세션(전역 상태가 이미 content_conn을 들고 있음)에서 주인공의
/// 현재 소속팀 정보 — [01_내선수](../../../04_UI기획/01_내선수.md) 상단
/// 요약바의 "소속팀" 표시용. 무소속(FA·아직 프로 미진입)이면 `None`.
Future<TeamOption?> getCurrentTeamInfo() =>
    RustLib.instance.api.crateApiGameGetCurrentTeamInfo();

/// [06_훈련_시스템](../../../02_기획/육성코어/06_훈련_시스템.md) §2 능력치
/// 노출 스탯 9종 — 훈련 탭의 주/보조 슬롯 드롭다운용. 순수 상수라 동기.
List<String> exposedStatNames() =>
    RustLib.instance.api.crateApiGameExposedStatNames();

/// §4 강도 다이얼 3단계 — 순수 상수라 동기.
List<String> trainingIntensityNames() =>
    RustLib.instance.api.crateApiGameTrainingIntensityNames();

Future<TrainingConfigInfo?> getTrainingConfig() =>
    RustLib.instance.api.crateApiGameGetTrainingConfig();

/// 훈련 슬롯 설정 — [01_내선수](../../../04_UI기획/01_내선수.md) §3 훈련
/// 탭이 호출. `repository::set_protagonist_training`을 그대로 감싼다(구종
/// 슬롯·신규 습득은 이번 서브분 스코프 밖 — 전체 구종 카탈로그를 조회할
/// 엔진 쿼리가 아직 없어 `new_pitch`는 항상 `None`으로 고정).
Future<void> setTraining({
  required String primaryStat,
  required String secondaryStat1,
  required String secondaryStat2,
  required String intensity,
}) => RustLib.instance.api.crateApiGameSetTraining(
  primaryStat: primaryStat,
  secondaryStat1: secondaryStat1,
  secondaryStat2: secondaryStat2,
  intensity: intensity,
);

/// [02_리그](../../../04_UI기획/02_리그.md) 결정5 "전 팀 풀 스카우팅"용 —
/// `league_id`를 주면 그 리그만, `None`이면 172팀 전부. 세션의
/// `content_conn`을 그대로 쓰므로(뉴게임 이후에만 호출 가능) 경로를 또
/// 안 받는다(`list_hs_teams`는 뉴게임 이전 캐릭터 생성 화면에서 쓰여
/// 경로가 필요했던 것과 다른 지점).
Future<List<TeamOption>> listTeams({String? leagueId}) =>
    RustLib.instance.api.crateApiGameListTeams(leagueId: leagueId);

Future<List<RosterPlayerInfo>> listRoster({required String teamId}) =>
    RustLib.instance.api.crateApiGameListRoster(teamId: teamId);

Future<List<ScheduleGameInfo>> getTeamSchedule({required String teamId}) =>
    RustLib.instance.api.crateApiGameGetTeamSchedule(teamId: teamId);

Future<List<StandingsRowInfo>> getStandings({required String leagueId}) =>
    RustLib.instance.api.crateApiGameGetStandings(leagueId: leagueId);

/// [02_리그](../../../04_UI기획/02_리그.md) §4 라이벌 탭 — `team_history.rivals`
/// (정적 콘텐츠, 지역·서사 페어링)만 반환한다. **개인 라이벌 관계
/// (관계도·아크단계 비교)는 이번 스코프에 없음** — `relationships`
/// 테이블이 스키마만 있고 실제로 채우는 로직이 엔진 어디에도 없어서다
/// (관계 시스템 자체가 아직 미구현, 05_히스토리_엔딩과 함께 후속 스코프).
/// 정확한 JSON 형태가 팀마다 다를 수 있어 원시 통과.
Future<String?> getTeamRivals({required String teamId}) =>
    RustLib.instance.api.crateApiGameGetTeamRivals(teamId: teamId);

Future<List<GameLogEntry>> getGameLog() =>
    RustLib.instance.api.crateApiGameGetGameLog();

Future<List<LeagueTransactionEntry>> getContractHistory() =>
    RustLib.instance.api.crateApiGameGetContractHistory();

Future<List<InjuryLogEntry>> getInjuryHistory() =>
    RustLib.instance.api.crateApiGameGetInjuryHistory();

/// 자발적 은퇴(§4 진입 3종 중 유일하게 플레이어가 임의 시점에 직접
/// 호출) — [08_은퇴](../../../04_UI기획/08_은퇴.md) §1. 나머지 두 트리거
/// (노쇠·부상)는 `advance()` 내부(시즌 경계·부상 판정)에서 엔진이 알아서
/// 감지해 `retirement` PendingAction을 만든다.
Future<void> declareRetirement() =>
    RustLib.instance.api.crateApiGameDeclareRetirement();

Future<CareerSummary> careerSummary() =>
    RustLib.instance.api.crateApiGameCareerSummary();

Future<List<SeasonLine>> careerTimeline() =>
    RustLib.instance.api.crateApiGameCareerTimeline();

/// [08_은퇴](../../../04_UI기획/08_은퇴.md) §2 "통산 기록 대시보드" —
/// **등급 매김 없이 순수 숫자**(05_히스토리_엔딩.md §4 "인생은 점수로
/// 판정하지 않는다"). "최종 자산"(08_개인_재정)·업적·라이벌전 하이라이트는
/// 해당 시스템 자체가 아직 엔진에 없어 이번 스코프엔 없음(10_구현_Phase_계획.md
/// §6-28 스코프 판단 참고).
class CareerSummary {
  final PlatformInt64 games;
  final PlatformInt64 wins;
  final PlatformInt64 losses;
  final PlatformInt64 noDecisions;
  final PlatformInt64 strikeouts;
  final PlatformInt64 inningsPitched;
  final double era;
  final bool retired;
  final String? retirementReason;

  const CareerSummary({
    required this.games,
    required this.wins,
    required this.losses,
    required this.noDecisions,
    required this.strikeouts,
    required this.inningsPitched,
    required this.era,
    required this.retired,
    this.retirementReason,
  });

  @override
  int get hashCode =>
      games.hashCode ^
      wins.hashCode ^
      losses.hashCode ^
      noDecisions.hashCode ^
      strikeouts.hashCode ^
      inningsPitched.hashCode ^
      era.hashCode ^
      retired.hashCode ^
      retirementReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CareerSummary &&
          runtimeType == other.runtimeType &&
          games == other.games &&
          wins == other.wins &&
          losses == other.losses &&
          noDecisions == other.noDecisions &&
          strikeouts == other.strikeouts &&
          inningsPitched == other.inningsPitched &&
          era == other.era &&
          retired == other.retired &&
          retirementReason == other.retirementReason;
}

/// [03_기록](../../../04_UI기획/03_기록.md) §1 "경기 로그" 탭 — `game_log`는
/// 압축 없이 경기별 전체 보존(07_매치_엔진.md §12). `detail_json`은
/// `{"grade","runs_allowed","opponent"}`(`apply_protagonist_evaluation`
/// 참고).
class GameLogEntry {
  final String gameId;
  final PlatformInt64 season;
  final String detailJson;

  const GameLogEntry({
    required this.gameId,
    required this.season,
    required this.detailJson,
  });

  @override
  int get hashCode => gameId.hashCode ^ season.hashCode ^ detailJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameLogEntry &&
          runtimeType == other.runtimeType &&
          gameId == other.gameId &&
          season == other.season &&
          detailJson == other.detailJson;
}

/// [03_기록](../../../04_UI기획/03_기록.md) §1 "부상·재활" 탭 —
/// `protagonist.injury.history`(08_부상_시스템.md §5, 부위·심각도·발생일).
/// **치료 선택·복귀 확정 시점은 이 로그에 없음** — `record_injury`가
/// 기록하는 `history` 항목은 발생 시점 스냅샷뿐이고, 치료법 확정
/// (`treat`)·완치(`clear_healed_injury`)는 `current` 필드만 갱신하고
/// `history`에 별도로 남기지 않는다(엔진 쪽에 그 로그를 추가하는 건
/// 이번 스코프 밖).
class InjuryLogEntry {
  final String part_;
  final String severity;
  final PlatformInt64 day;

  const InjuryLogEntry({
    required this.part_,
    required this.severity,
    required this.day,
  });

  @override
  int get hashCode => part_.hashCode ^ severity.hashCode ^ day.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InjuryLogEntry &&
          runtimeType == other.runtimeType &&
          part_ == other.part_ &&
          severity == other.severity &&
          day == other.day;
}

/// [03_기록](../../../04_UI기획/03_기록.md) §1 "계약·이력" 탭 — `league_transactions`
/// 중 `'contract'`(방출/체결, `process_protagonist_contract`·
/// `resolve_contract_nego`가 기록)·`'trade'`(`resolve_trade_decision`이
/// 기록) 종류만. `'champion'`(리그 전체 우승팀 기록)은 주인공 개인 이력이
/// 아니라 제외. **드래프트 로그는 없음** — 진로 갈림길(고교→프로 진입)
/// 자체가 엔진에 없어(§6-19에서 이미 확인) 드래프트 이벤트가 발생할
/// 수가 없다.
class LeagueTransactionEntry {
  final String id;
  final PlatformInt64 day;
  final String kind;
  final String detailJson;

  const LeagueTransactionEntry({
    required this.id,
    required this.day,
    required this.kind,
    required this.detailJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^ day.hashCode ^ kind.hashCode ^ detailJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LeagueTransactionEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          day == other.day &&
          kind == other.kind &&
          detailJson == other.detailJson;
}

@freezed
sealed class MatchStepInfo with _$MatchStepInfo {
  const MatchStepInfo._();

  const factory MatchStepInfo.awaitingPitch({
    required String batterId,
    required int balls,
    required int strikes,
    required bool highLeverage,
  }) = MatchStepInfo_AwaitingPitch;
  const factory MatchStepInfo.gameOver({
    required int homeRuns,
    required int awayRuns,
  }) = MatchStepInfo_GameOver;
}

/// 현재 진행일·시즌 — 전용 화면 없이도 "시즌종료"를 넘겼는지 UI가 배지로
/// 보여줄 수 있게 하는 최소 조회. `season`은 `season_meta`에 아직 한 번도
/// 안 쓰였으면(뉴게임 직후) 0.
class MetaStatusInfo {
  final PlatformInt64 currentDay;
  final PlatformInt64 season;

  const MetaStatusInfo({required this.currentDay, required this.season});

  @override
  int get hashCode => currentDay.hashCode ^ season.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetaStatusInfo &&
          runtimeType == other.runtimeType &&
          currentDay == other.currentDay &&
          season == other.season;
}

/// PendingAction 하나 — `04_게임루프.md` §3의 7종 중 지금 대기 중인 것.
/// `payload_json`은 타입별로 형태가 다른 JSON — Dart가 `kind`를 보고
/// 어떤 화면으로 갈지 고르고(전용화면은 후속 서브분), 그 화면이 필요한
/// 필드만 꺼내 쓴다.
class PendingActionInfo {
  final String id;
  final String kind;
  final String urgency;
  final PlatformInt64 createdDay;
  final String payloadJson;

  const PendingActionInfo({
    required this.id,
    required this.kind,
    required this.urgency,
    required this.createdDay,
    required this.payloadJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      urgency.hashCode ^
      createdDay.hashCode ^
      payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingActionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          urgency == other.urgency &&
          createdDay == other.createdDay &&
          payloadJson == other.payloadJson;
}

/// 주인공 상태 — 이름·능력치·라이브상태·계약·부상·보유구종. 유연한
/// 블롭은 JSON 원시 통과(모듈 문서 참고) — Dart는 표시용으로만 읽는다.
class ProtagonistStatusInfo {
  final String name;
  final String statsJson;
  final String liveStateJson;
  final String contractJson;
  final String injuryJson;
  final String pitchesJson;

  const ProtagonistStatusInfo({
    required this.name,
    required this.statsJson,
    required this.liveStateJson,
    required this.contractJson,
    required this.injuryJson,
    required this.pitchesJson,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      statsJson.hashCode ^
      liveStateJson.hashCode ^
      contractJson.hashCode ^
      injuryJson.hashCode ^
      pitchesJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtagonistStatusInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          statsJson == other.statsJson &&
          liveStateJson == other.liveStateJson &&
          contractJson == other.contractJson &&
          injuryJson == other.injuryJson &&
          pitchesJson == other.pitchesJson;
}

/// 로스터 한 명 — [02_리그](../../../04_UI기획/02_리그.md) §1. NPC는
/// S~D 등급이 없다(§1 "등급은 주인공 전용") — 능력치+포지션+보유구종만.
/// 개인 통산 성적은 그 자체가 엔진에 없어(계속 이월 항목) 이번에도 없음.
class RosterPlayerInfo {
  final String id;
  final String name;
  final String position;
  final PlatformInt64 age;
  final String statsJson;
  final String? pitchesJson;

  const RosterPlayerInfo({
    required this.id,
    required this.name,
    required this.position,
    required this.age,
    required this.statsJson,
    this.pitchesJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      position.hashCode ^
      age.hashCode ^
      statsJson.hashCode ^
      pitchesJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RosterPlayerInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          position == other.position &&
          age == other.age &&
          statsJson == other.statsJson &&
          pitchesJson == other.pitchesJson;
}

/// [02_리그](../../../04_UI기획/02_리그.md) §2 일정 탭 — `team_id`의 전체
/// 스케줄(지난 결과 + 다가오는 경기). `result_json`이 `None`이면 아직 안
/// 열린 경기.
class ScheduleGameInfo {
  final String gameId;
  final PlatformInt64 day;
  final String home;
  final String away;
  final String? resultJson;

  const ScheduleGameInfo({
    required this.gameId,
    required this.day,
    required this.home,
    required this.away,
    this.resultJson,
  });

  @override
  int get hashCode =>
      gameId.hashCode ^
      day.hashCode ^
      home.hashCode ^
      away.hashCode ^
      resultJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduleGameInfo &&
          runtimeType == other.runtimeType &&
          gameId == other.gameId &&
          day == other.day &&
          home == other.home &&
          away == other.away &&
          resultJson == other.resultJson;
}

/// [08_은퇴](../../../04_UI기획/08_은퇴.md) §2 "커리어 타임라인 그래프" —
/// `career_history`(시즌별 한 줄, `season_rollover`가 채움)를 그대로
/// 노출. `line_json`은 `{"games","wins","losses","no_decisions",
/// "strikeouts","innings_pitched","era"}` 형태.
class SeasonLine {
  final PlatformInt64 season;
  final String lineJson;

  const SeasonLine({required this.season, required this.lineJson});

  @override
  int get hashCode => season.hashCode ^ lineJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeasonLine &&
          runtimeType == other.runtimeType &&
          season == other.season &&
          lineJson == other.lineJson;
}

/// [02_리그](../../../04_UI기획/02_리그.md) §3 순위 탭 — `league_id` 소속
/// 팀들의 승률 내림차순 순위. `standings.rank` 컬럼은 시즌 중엔 갱신 안
/// 되고 `season_rollover` 때만 확정되므로(`repository::update_standings`
/// 참고), 여기 `rank`는 이 조회 시점에 재계산한 값 — 정렬·표시 포맷팅일
/// 뿐 승패 판정 자체가 아니라 "UI가 해도 됨: 정렬"(03_구조.md §3)에 해당.
/// 로스터가 없어(방금 뉴게임 직후 등) `standings` 행이 아직 없는 팀은
/// 0승0패로 취급.
class StandingsRowInfo {
  final String teamId;
  final PlatformInt64 rank;
  final PlatformInt64 wins;
  final PlatformInt64 losses;
  final PlatformInt64 ties;

  const StandingsRowInfo({
    required this.teamId,
    required this.rank,
    required this.wins,
    required this.losses,
    required this.ties,
  });

  @override
  int get hashCode =>
      teamId.hashCode ^
      rank.hashCode ^
      wins.hashCode ^
      losses.hashCode ^
      ties.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StandingsRowInfo &&
          runtimeType == other.runtimeType &&
          teamId == other.teamId &&
          rank == other.rank &&
          wins == other.wins &&
          losses == other.losses &&
          ties == other.ties;
}

/// 캐릭터 생성 스텝3~4(지역·학교 선택)용 — 고교 리그 팀 전부와 팀특성
/// 3슬롯. 지역별 그룹핑·학교 카드 비주얼은 06_캐릭터생성.md 자체가
/// "열린 세부 — 아트 단계"로 이미 미뤄둔 항목이라, 이번 스코프는 평평한
/// 목록만 준다 — Dart가 `meta_json`에서 이름 등 표시 필드를 꺼내 쓴다.
class TeamOption {
  final String teamId;
  final String leagueId;
  final String metaJson;
  final String philosophy;
  final String resource;
  final String status;

  const TeamOption({
    required this.teamId,
    required this.leagueId,
    required this.metaJson,
    required this.philosophy,
    required this.resource,
    required this.status,
  });

  @override
  int get hashCode =>
      teamId.hashCode ^
      leagueId.hashCode ^
      metaJson.hashCode ^
      philosophy.hashCode ^
      resource.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TeamOption &&
          runtimeType == other.runtimeType &&
          teamId == other.teamId &&
          leagueId == other.leagueId &&
          metaJson == other.metaJson &&
          philosophy == other.philosophy &&
          resource == other.resource &&
          status == other.status;
}

/// 현재 훈련 설정 — 한 번도 설정 안 했으면 `None`(§1 "훈련 계획을 아직
/// 안 짰다"는 자연스러운 초기 상태, `set_protagonist_training` 문서 참고).
class TrainingConfigInfo {
  final String primaryStat;
  final List<String> secondaryStats;
  final String intensity;
  final String? newPitch;

  const TrainingConfigInfo({
    required this.primaryStat,
    required this.secondaryStats,
    required this.intensity,
    this.newPitch,
  });

  @override
  int get hashCode =>
      primaryStat.hashCode ^
      secondaryStats.hashCode ^
      intensity.hashCode ^
      newPitch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrainingConfigInfo &&
          runtimeType == other.runtimeType &&
          primaryStat == other.primaryStat &&
          secondaryStats == other.secondaryStats &&
          intensity == other.intensity &&
          newPitch == other.newPitch;
}

/// [07_전환화면](../../../04_UI기획/07_전환화면.md) §5 "3옵션 비교표" —
/// `injuryTreatment` PendingAction의 `choice_id`로 그대로 쓸 수 있는
/// `name`(`resolve_choice`가 기대하는 정확한 문자열, `sim::injury::TREATMENTS`)
/// 과 함께 이탈기간(`sim::injury::treated_recovery_days`, 실제 계산값)·
/// 재발위험·완치도(08_부상_시스템.md §4 표의 정성적 설명 — 수술/재활/
/// 무리한복귀 셋 다 즉시-판정형이라 정확한 확률은 선택 시점(`treat`)에야
/// 나오므로 사전 비교표는 문서가 확정해둔 상대적 설명 문구로 표시).
/// 순수 계산이라 동기.
class TreatmentOption {
  final String name;
  final PlatformInt64 recoveryDays;
  final String riskLabel;
  final String recoveryQualityLabel;

  const TreatmentOption({
    required this.name,
    required this.recoveryDays,
    required this.riskLabel,
    required this.recoveryQualityLabel,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      recoveryDays.hashCode ^
      riskLabel.hashCode ^
      recoveryQualityLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TreatmentOption &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          recoveryDays == other.recoveryDays &&
          riskLabel == other.riskLabel &&
          recoveryQualityLabel == other.recoveryQualityLabel;
}
