// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'game.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `avg_rank_from_season_ranks`, `from_line`, `from_line`, `standings_rows`, `stars_from_group_position`, `tournament_display_name`, `tournament_includes_team`, `with_state_mut`, `with_state`, `world_seed`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GameState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

Future<PregameScoutingInfo> getPregameScouting({
  required String gameId,
  required String homeTeamId,
  required String awayTeamId,
}) => RustLib.instance.api.crateApiGameGetPregameScouting(
  gameId: gameId,
  homeTeamId: homeTeamId,
  awayTeamId: awayTeamId,
);

Future<BatterProfileInfo> getBatterProfile({required String npcId}) =>
    RustLib.instance.api.crateApiGameGetBatterProfile(npcId: npcId);

/// 매치 화면 박스스코어(migration v26, 대화 2026-07-25) — 이닝별
/// `[{"inning","top_of_inning","runs","hits","walks"}, ...]` JSON 배열.
/// 진행 중인 매치 세션이 없으면 `None`(모듈 문서 "JSON 원시 통과" 관례 —
/// Dart가 dart:convert로 표시용으로만 읽는다).
Future<String?> getInningLog() =>
    RustLib.instance.api.crateApiGameGetInningLog();

Future<MatchVenueInfo?> getMatchVenue() =>
    RustLib.instance.api.crateApiGameGetMatchVenue();

/// 매치 화면 타자 카드 "이번 경기" 라인(migration v26, 대화 2026-07-25) —
/// `PlayerBattingStats`와 대칭이지만 시즌 전체가 아니라 지금 진행 중인
/// 경기 하나만. 그 선수가 이번 경기에 아직 타석에 서지 않았거나 매치
/// 세션이 없으면 0으로 채운 라인.
Future<PlayerBattingStats> getBatterGameStats({required String npcId}) =>
    RustLib.instance.api.crateApiGameGetBatterGameStats(npcId: npcId);

/// 매치 화면 타자 카드 "시즌 전체" 라인(대화 2026-07-25) — `get_team_season_batting_stats`
/// 와 같은 소스(진행 중인 `season_stats` 합산)를 선수 한 명만 뽑는 얇은
/// 래퍼. `get_player_career_batting_stats`(과거 확정 시즌들 통산)와는
/// 시즌 범위가 다르다.
Future<PlayerBattingStats> getPlayerSeasonBattingStats({
  required String npcId,
}) =>
    RustLib.instance.api.crateApiGameGetPlayerSeasonBattingStats(npcId: npcId);

/// 뉴게임 — [07_주인공_생성](../../../02_기획/07_주인공_생성.md) §1의 7단계
/// 흐름 중 실제 데이터를 만드는 마지막 단계(스텝 1~6은 Dart 쪽 폼 상태일
/// 뿐 엔진 호출이 아님). 결정적 seed로 배경 세계(172팀 로스터+일정)를
/// 먼저 만든 뒤 주인공을 생성해 전역 세션에 올린다.
///
/// `slot_path`가 `Some`이면 [02_데이터](../../../03_설계/02_데이터.md) §4
/// "파일=슬롯"대로 그 경로에 실제 파일을 만들어 세이브가 영속된다(I7
/// 9차분) — `None`이면 이전처럼 인메모리(테스트·일회성 검증용). 실제
/// 파일 경로 생성(앱 데이터 폴더 하위 `slot_<id>.db`)은 Dart가 담당 —
/// 엔진은 플랫폼 경로 규칙을 모른다(다른 `*_db_path` 인자들과 같은 관례).
Future<void> newGame({
  required String contentDbPath,
  required PlatformInt64 canonicalSeed,
  required String name,
  required String handedness,
  required String schoolTeamId,
  required String archetype,
  String? secondPitch,
  String? slotPath,
}) => RustLib.instance.api.crateApiGameNewGame(
  contentDbPath: contentDbPath,
  canonicalSeed: canonicalSeed,
  name: name,
  handedness: handedness,
  schoolTeamId: schoolTeamId,
  archetype: archetype,
  secondPitch: secondPitch,
  slotPath: slotPath,
);

/// `dir` 아래 `.db` 파일을 전부 슬롯으로 훑는다. **손상되거나 아직
/// 캐릭터 생성 전인 파일은 조용히 건너뛴다** — 슬롯 하나가 깨졌다고
/// 목록 전체가 에러로 죽으면 안 되고, `new_game`이 캐릭터 생성까지
/// 원자적으로 끝내므로 "생성 중" 상태의 파일도 사실상 없다.
Future<List<SlotSummary>> listSlots({required String dir}) =>
    RustLib.instance.api.crateApiGameListSlots(dir: dir);

/// 메인 메뉴 "이어하기" — 기존 슬롯 파일을 열어 전역 세션에 올린다.
Future<void> loadSlot({
  required String slotPath,
  required String contentDbPath,
}) => RustLib.instance.api.crateApiGameLoadSlot(
  slotPath: slotPath,
  contentDbPath: contentDbPath,
);

/// [02_데이터](../../../03_설계/02_데이터.md) §4 "삭제 = 파일 삭제". 지울
/// 슬롯이 마침 지금 활성 세션이 열어둔 그 파일이면(예: 슬롯 1을 플레이
/// 중 메인 메뉴로 돌아가 "새로하기"로 슬롯 1을 다시 고름) `STATE`가
/// 핸들을 쥐고 있어 Windows에서 삭제가 "다른 프로세스가 사용 중"으로
/// 실패한다(대화 2026-07-25) — 먼저 전역 세션을 비워 핸들을 놓아준다.
Future<void> deleteSlot({required String slotPath}) =>
    RustLib.instance.api.crateApiGameDeleteSlot(slotPath: slotPath);

/// 진행(Continue) — [04_게임루프](../../../03_설계/04_게임루프.md) §2
/// `advance()`를 그대로 노출. 정지점(새 PendingAction 또는 주인공 경기)
/// 까지 하루씩 전진한 뒤 대기 목록을 반환한다.
Future<List<PendingActionInfo>> advance() =>
    RustLib.instance.api.crateApiGameAdvance();

/// PendingAction 응답 — 타입별 `choice_id` 형식은
/// [04_게임루프](../../../03_설계/04_게임루프.md) §3·엔진 `resolve_choice`
/// 문서 참고(`game`: 모드 문자열, `pitch`: `"구종:코스"`, `injuryTreatment`:
/// 치료법, `contractNego`: `"accept:team_id"`/`"counter:team_id:금액"`/
/// `"reject"`, `tradeDecision`: `"accept"`/`"reject"`). 결과가 `Some`이면
/// 매치가 계속 진행 중이라는 뜻 — Dart는 `AwaitingPitch`면 다음 1구를
/// 위해 다시 이 함수를 호출하고, `GameOver`면 경기 요약으로 넘어간다.
Future<MatchStepInfo?> resolveChoice({
  required String actionId,
  required String choiceId,
}) => RustLib.instance.api.crateApiGameResolveChoice(
  actionId: actionId,
  choiceId: choiceId,
);

Future<ProtagonistStatusInfo> getProtagonistStatus() =>
    RustLib.instance.api.crateApiGameGetProtagonistStatus();

/// 지금 세션의 미해결 PendingAction 전체 — 화면 재진입(예: 매치 중 다른
/// 탭 갔다가 복귀) 시 재조회용. `advance`/`resolve_choice`가 반환하는
/// 목록과 항상 같은 소스(`pending_actions` 테이블)를 본다.
Future<List<PendingActionInfo>> getPendingActions() =>
    RustLib.instance.api.crateApiGameGetPendingActions();

Future<MetaStatusInfo> getMetaStatus() =>
    RustLib.instance.api.crateApiGameGetMetaStatus();

Future<AcademicsStatusInfo?> getAcademicsStatus() =>
    RustLib.instance.api.crateApiGameGetAcademicsStatus();

/// 주간 학습모드 변경 — `sim::academics::STUDY_MODES`(focus/normal/rest/sleep) 중 하나.
Future<void> setWeeklyStudyMode({required String mode}) =>
    RustLib.instance.api.crateApiGameSetWeeklyStudyMode(mode: mode);

/// 대학 전공 확정 — `sim::academics::UNIVERSITY_MAJORS`(체육교육/스포츠과학/일반전공) 중 하나.
Future<void> setUniversityMajor({required String major}) =>
    RustLib.instance.api.crateApiGameSetUniversityMajor(major: major);

/// 과목 석차백분율(1=상위)을 9등급으로 — 학업 탭 과목별 표에서 순수 계산이라
/// I/O·락 없이 동기 호출로 둔다(`power_names()`와 같은 패턴).
PlatformInt64 percentileToGrade({required double percentile}) =>
    RustLib.instance.api.crateApiGamePercentileToGrade(percentile: percentile);

/// 1구 조작 집중뷰의 구위 다이얼 3단계 — `sim::pitch::Power`의 라벨
/// 그대로(`resolve_choice`의 `"구종:x:y:구위"` choice_id 마지막 파트에
/// 이 이름을 그대로 넣으면 된다). 투구 위치는 더 이상 고정 목록이 아니라
/// 연속좌표(대화 2026-07-25, 매치 화면 재설계)라 별도 이름 목록이 없다 —
/// Dart 쪽 코스 캔버스가 탭 위치를 직접 x,y로 변환해 보낸다. 순수 계산
/// (I/O·락 없음)이라 동기 호출로 둔다.
List<String> powerNames() => RustLib.instance.api.crateApiGamePowerNames();

CalendarDateInfo calendarDateForDay({required PlatformInt64 day}) =>
    RustLib.instance.api.crateApiGameCalendarDateForDay(day: day);

List<TreatmentOption> treatmentOptions({required String severity}) =>
    RustLib.instance.api.crateApiGameTreatmentOptions(severity: severity);

Future<List<TeamOption>> listHsTeams({required String contentDbPath}) =>
    RustLib.instance.api.crateApiGameListHsTeams(contentDbPath: contentDbPath);

Future<List<HsSchoolDetail>> listHsSchoolDetails({
  required String contentDbPath,
}) => RustLib.instance.api.crateApiGameListHsSchoolDetails(
  contentDbPath: contentDbPath,
);

/// 지금 세션(전역 상태가 이미 content_conn을 들고 있음)에서 주인공의
/// 현재 소속팀 정보 — [01_내선수](../../../04_UI기획/01_내선수.md) 상단
/// 요약바의 "소속팀" 표시용. 무소속(FA·아직 프로 미진입)이면 `None`.
Future<TeamOption?> getCurrentTeamInfo() =>
    RustLib.instance.api.crateApiGameGetCurrentTeamInfo();

/// [06_훈련_시스템](../../../02_기획/육성코어/06_훈련_시스템.md) §2 능력치
/// 노출 스탯 9종 — 훈련 탭의 주/보조 슬롯 드롭다운용. 순수 상수라 동기.
List<String> exposedStatNames() =>
    RustLib.instance.api.crateApiGameExposedStatNames();

/// §4 강도 다이얼 3단계 — 순수 상수라 동기.
List<String> trainingIntensityNames() =>
    RustLib.instance.api.crateApiGameTrainingIntensityNames();

/// 순수 상수라 동기.
List<TrainingTypeInfo> trainingTypeOptions() =>
    RustLib.instance.api.crateApiGameTrainingTypeOptions();

List<PitcherArchetypeInfo> pitcherArchetypeInfo() =>
    RustLib.instance.api.crateApiGamePitcherArchetypeInfo();

Future<TrainingConfigInfo?> getTrainingConfig() =>
    RustLib.instance.api.crateApiGameGetTrainingConfig();

/// 훈련 슬롯 설정 — [01_내선수](../../../04_UI기획/01_내선수.md) §3 훈련
/// 탭이 호출. `repository::set_protagonist_training`을 그대로 감싼다.
/// `new_pitch`는 신규 구종 습득 슬롯(대화 2026-07-21) — `pitch_type_names`
/// 로 받은 카탈로그 중 아직 안 배운 구종 하나를 골라 넘기면 그 주부터
/// `pitch_weeks` 진행도가 쌓인다. `mastery_pitch`는 이미 아는 구종의
/// 마스터리 단계를 올리는 슬롯(05_구종_시스템.md §2, 대화 2026-07-23) —
/// 둘 중 하나만 넘길 수 있다.
Future<void> setTraining({
  required String primaryTraining,
  required String secondaryTraining,
  required String intensity,
  String? newPitch,
  String? masteryPitch,
}) => RustLib.instance.api.crateApiGameSetTraining(
  primaryTraining: primaryTraining,
  secondaryTraining: secondaryTraining,
  intensity: intensity,
  newPitch: newPitch,
  masteryPitch: masteryPitch,
);

/// 신규 구종 습득 슬롯 드롭다운용 — [05_구종_시스템](../../../02_기획/육성코어/05_구종_시스템.md)
/// §1의 10종 카탈로그(`content.db`의 `pitch_types`). 세션이 이미 열려있는
/// 상태(내 정보 화면)에서만 호출되므로 `list_hs_teams`처럼 경로를 따로 안
/// 받고 세션의 `content_conn`을 그대로 씀.
Future<List<String>> pitchTypeNames() =>
    RustLib.instance.api.crateApiGamePitchTypeNames();

/// "신규 구종 습득" 슬롯 후보 조회 — [05_구종_시스템](../../../02_기획/육성코어/05_구종_시스템.md)
/// §3 습득 조건(스탯 임계값)을 실제로 반영한다(대화 2026-07-25, 이전엔
/// `pitch_type_names`에서 이미 보유한 것만 뺀 카탈로그 전체를 그대로
/// 드롭다운에 뿌렸음). 보유 구종 상한 도달 시 둘 다 빈 값(카드가 "상한"
/// 안내를 보여줌). `eligible`이 비었으면 `next_candidate`로 가장 가까운
/// 목표 하나만 안내 — 카탈로그 전체를 드러내지 않으면서도 완전히
/// 깜깜이는 아니게.
Future<LearnablePitchesInfo> learnablePitches() =>
    RustLib.instance.api.crateApiGameLearnablePitches();

/// 보유 구종 상한(05_구종_시스템.md §3, 대화 2026-07-24) — 순수 상수라 동기.
int maxKnownPitches() => RustLib.instance.api.crateApiGameMaxKnownPitches();

/// 캐릭터 생성 "개인 신체" 페이지 혈액형 드롭다운용 — 순수 상수라 동기.
List<String> bloodTypeNames() =>
    RustLib.instance.api.crateApiGameBloodTypeNames();

/// 캐릭터 생성 "개인 신체" 페이지 출신지역 드롭다운용(8권역) — 순수 상수라 동기.
List<String> hometownRegionNames() =>
    RustLib.instance.api.crateApiGameHometownRegionNames();

Future<ProtagonistProfileInfo?> getProtagonistProfile() =>
    RustLib.instance.api.crateApiGameGetProtagonistProfile();

/// 캐릭터 생성 화면이 `newGame` 직후 호출 — `set_training`과 동일하게
/// `repository::set_protagonist_profile`을 그대로 감싼다.
Future<void> setProtagonistProfile({
  required PlatformInt64 birthMonth,
  required PlatformInt64 birthDay,
  required double heightCm,
  required double weightKg,
  required String bloodType,
  required String hometown,
  required PlatformInt64 jerseyNumber,
}) => RustLib.instance.api.crateApiGameSetProtagonistProfile(
  birthMonth: birthMonth,
  birthDay: birthDay,
  heightCm: heightCm,
  weightKg: weightKg,
  bloodType: bloodType,
  hometown: hometown,
  jerseyNumber: jerseyNumber,
);

/// [02_리그](../../../04_UI기획/02_리그.md) 결정5 "전 팀 풀 스카우팅"용 —
/// `league_id`를 주면 그 리그만, `None`이면 172팀 전부. 세션의
/// `content_conn`을 그대로 쓰므로(뉴게임 이후에만 호출 가능) 경로를 또
/// 안 받는다(`list_hs_teams`는 뉴게임 이전 캐릭터 생성 화면에서 쓰여
/// 경로가 필요했던 것과 다른 지점).
Future<List<TeamOption>> listTeams({String? leagueId}) =>
    RustLib.instance.api.crateApiGameListTeams(leagueId: leagueId);

/// 리그 화면 "로스터" 탭용 — 선수만(감독/코치/구단주 제외, 대화
/// 2026-07-24에서 발견한 버그 수정: 예전엔 이 가드가 없어 스태프가
/// 전술력·신뢰형성력 같은 낯선 숫자를 달고 선수단 목록에 섞여 나왔다).
/// 스태프는 `list_team_staff`로 따로 조회.
Future<List<RosterPlayerInfo>> listRoster({required String teamId}) =>
    RustLib.instance.api.crateApiGameListRoster(teamId: teamId);

/// 리그 화면 "로스터" 탭의 스태프 카드용(대화 2026-07-24) — 감독/코치/
/// 구단주만. `list_roster`와 같은 모양(`RosterPlayerInfo`)을 그대로
/// 재사용해 Dart 쪽 파싱 로직을 공유할 수 있게 한다.
Future<List<RosterPlayerInfo>> listTeamStaff({required String teamId}) =>
    RustLib.instance.api.crateApiGameListTeamStaff(teamId: teamId);

/// 리그 화면 로스터 탭의 "이번 시즌" 타자 성적(Phase 5) — 그 팀 타자
/// 전원(포지션이 투수 3종이 아닌 선수)의 진행 중 `season_stats` 합산.
Future<List<PlayerBattingStats>> getTeamSeasonBattingStats({
  required String teamId,
}) =>
    RustLib.instance.api.crateApiGameGetTeamSeasonBattingStats(teamId: teamId);

/// 리그 화면 로스터 탭의 "이번 시즌" 투수 성적(Phase 5) — 그 팀 투수
/// 전원(선발/중계/마무리)의 진행 중 `season_stats` 합산.
Future<List<PlayerPitchingStats>> getTeamSeasonPitchingStats({
  required String teamId,
}) =>
    RustLib.instance.api.crateApiGameGetTeamSeasonPitchingStats(teamId: teamId);

/// 선수 한 명의 통산(시즌 아카이브 전체 합산) 타자 기록(Phase 5) —
/// `npc_season_history`(과거 확정 시즌들) 전체를 합산. 이번 시즌 진행분은
/// 아직 아카이브되지 않았으므로(시즌 종료 시점에만 archive) 포함 안 됨 —
/// `get_team_season_batting_stats`가 그 몫을 담당.
Future<PlayerBattingStats> getPlayerCareerBattingStats({
  required String playerId,
}) => RustLib.instance.api.crateApiGameGetPlayerCareerBattingStats(
  playerId: playerId,
);

/// `get_player_career_batting_stats`와 대칭인 투수 쪽.
Future<PlayerPitchingStats> getPlayerCareerPitchingStats({
  required String playerId,
}) => RustLib.instance.api.crateApiGameGetPlayerCareerPitchingStats(
  playerId: playerId,
);

/// 캐릭터 생성 화면 "학교 선택" 미리보기(대화 2026-07-23) — 아직 새 게임을
/// 시작하지 않아 슬롯이 없는 상태에서도 `world_seed`(캐릭터 생성 화면
/// 진입 시 한 번 고정된 시드, Dart가 `new_game`에도 그대로 넘김)만 있으면
/// `list_roster`와 같은 모양의 결과를 미리 보여줄 수 있다. `list_roster`와
/// 달리 활성 세션이 필요 없다(`list_hs_school_details`와 같은 패턴 —
/// `content_db_path`로 독립 커넥션만 연다).
Future<List<RosterPlayerInfo>> previewHsRoster({
  required String contentDbPath,
  required PlatformInt64 worldSeed,
  required String teamId,
}) => RustLib.instance.api.crateApiGamePreviewHsRoster(
  contentDbPath: contentDbPath,
  worldSeed: worldSeed,
  teamId: teamId,
);

Future<List<ScheduleGameInfo>> getTeamSchedule({required String teamId}) =>
    RustLib.instance.api.crateApiGameGetTeamSchedule(teamId: teamId);

Future<List<StandingsRowInfo>> getStandings({required String leagueId}) =>
    RustLib.instance.api.crateApiGameGetStandings(leagueId: leagueId);

/// 리그 탭 "진행중인 대회" 세션 — 팀이 소속된 리그 순위 카드(항상 1개) +
/// 이번 시즌 참가한 대회 카드(있는 만큼, `tournaments.season`이 지금
/// 시즌과 같고 `participants`에 이 팀이 포함된 것만). 대회 카드는
/// 우승/탈락이 확정돼도(그 시즌 동안은) 그대로 유지되고, 시즌이
/// 바뀌면 자연히 사라졌다가 다시 참가하면 새로 나타난다 — **중간에
/// 대진에서 탈락해도(다른 팀들 경기가 아직 안 끝났으면) 대회 전체가
/// `status='done'`이 되기 전까지는 "진행 중"으로 보임**(1차 축소안 —
/// 매치업별 실시간 탈락 판정은 이월).
Future<List<CompetitionCardInfo>> listActiveCompetitions({
  required String teamId,
}) => RustLib.instance.api.crateApiGameListActiveCompetitions(teamId: teamId);

/// 대회 카드를 탭했을 때 — 라운드별 매치업 전부(진행 중인 라운드는 아직
/// `home_runs`/`away_runs`가 `None`인 행으로, 이미 끝난 라운드는 채워진
/// 채로) 반환. `round`·`day` 오름차순이라 UI가 그대로 라운드별로 묶어
/// 그리면 된다.
Future<TournamentBracketInfo> getTournamentBracket({
  required String tournamentId,
}) => RustLib.instance.api.crateApiGameGetTournamentBracket(
  tournamentId: tournamentId,
);

/// [02_리그](../../../04_UI기획/02_리그.md) §4 라이벌 탭 — `team_history.rivals`
/// (정적 콘텐츠, 지역·서사 페어링)만 반환한다. **개인 라이벌 관계
/// (관계도·아크단계 비교)는 이번 스코프에 없음** — `relationships`
/// 테이블이 스키마만 있고 실제로 채우는 로직이 엔진 어디에도 없어서다
/// (관계 시스템 자체가 아직 미구현, 05_히스토리_엔딩과 함께 후속 스코프).
/// 정확한 JSON 형태가 팀마다 다를 수 있어 원시 통과.
Future<String?> getTeamRivals({required String teamId}) =>
    RustLib.instance.api.crateApiGameGetTeamRivals(teamId: teamId);

Future<List<GameLogEntry>> getGameLog() =>
    RustLib.instance.api.crateApiGameGetGameLog();

Future<List<LeagueTransactionEntry>> getContractHistory() =>
    RustLib.instance.api.crateApiGameGetContractHistory();

Future<List<InjuryLogEntry>> getInjuryHistory() =>
    RustLib.instance.api.crateApiGameGetInjuryHistory();

/// 자발적 은퇴(§4 진입 3종 중 유일하게 플레이어가 임의 시점에 직접
/// 호출) — [08_은퇴](../../../04_UI기획/08_은퇴.md) §1. 나머지 두 트리거
/// (노쇠·부상)는 `advance()` 내부(시즌 경계·부상 판정)에서 엔진이 알아서
/// 감지해 `retirement` PendingAction을 만든다.
Future<void> declareRetirement() =>
    RustLib.instance.api.crateApiGameDeclareRetirement();

Future<CareerSummary> careerSummary() =>
    RustLib.instance.api.crateApiGameCareerSummary();

/// 매치 화면 투수 카드 "이번 시즌" 성적(대화 2026-07-25) — `career_summary`와
/// 같은 모양이지만 통산 전체가 아니라 진행 중인 시즌만(`aggregate_game_log`의
/// `season` 필터, `get_meta_status().season`과 동일한 값 사용).
Future<CareerSummary> getProtagonistSeasonSummary() =>
    RustLib.instance.api.crateApiGameGetProtagonistSeasonSummary();

Future<List<SeasonLine>> careerTimeline() =>
    RustLib.instance.api.crateApiGameCareerTimeline();

Future<List<CareerEventInfo>> getCareerEvents() =>
    RustLib.instance.api.crateApiGameGetCareerEvents();

Future<List<AchievementInfo>> getAchievements() =>
    RustLib.instance.api.crateApiGameGetAchievements();

Future<List<RelationshipInfo>> getRelationships() =>
    RustLib.instance.api.crateApiGameGetRelationships();

Future<List<InboxMessageInfo>> getInbox() =>
    RustLib.instance.api.crateApiGameGetInbox();

/// 메시지함 화면(I7)의 읽음 처리 — `repository::mark_inbox_read` 그대로.
Future<void> markInboxRead({required String id}) =>
    RustLib.instance.api.crateApiGameMarkInboxRead(id: id);

/// 학업 시스템 상태 — 고교(`league:hs`)·대학(`league:univ`) 스테이지가
/// 아니면 `None`(Dart는 이 값 하나로 학업 탭 노출 여부를 그대로 판정 —
/// 계획서 "고교·대학 스테이지에서만 탭 노출"). `subject_scores_json`은
/// 과목 5개(국/영/수/사/과) 각각의 `percentile`/`attendance`/`assignment`
/// 원시 JSON 통과(모듈 문서의 "JSON 원시 통과" 관례 그대로).
class AcademicsStatusInfo {
  final bool attendsUniversity;
  final String weeklyStudyMode;
  final String subjectScoresJson;
  final double examAccumScore;
  final PlatformInt64? lastGrade;
  final String lastGradeRisk;
  final bool eligibilityBlocked;
  final String? universityMajor;
  final bool majorSelected;
  final String nextExamLabel;
  final PlatformInt64 weeksUntilNextExam;

  const AcademicsStatusInfo({
    required this.attendsUniversity,
    required this.weeklyStudyMode,
    required this.subjectScoresJson,
    required this.examAccumScore,
    this.lastGrade,
    required this.lastGradeRisk,
    required this.eligibilityBlocked,
    this.universityMajor,
    required this.majorSelected,
    required this.nextExamLabel,
    required this.weeksUntilNextExam,
  });

  @override
  int get hashCode =>
      attendsUniversity.hashCode ^
      weeklyStudyMode.hashCode ^
      subjectScoresJson.hashCode ^
      examAccumScore.hashCode ^
      lastGrade.hashCode ^
      lastGradeRisk.hashCode ^
      eligibilityBlocked.hashCode ^
      universityMajor.hashCode ^
      majorSelected.hashCode ^
      nextExamLabel.hashCode ^
      weeksUntilNextExam.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcademicsStatusInfo &&
          runtimeType == other.runtimeType &&
          attendsUniversity == other.attendsUniversity &&
          weeklyStudyMode == other.weeklyStudyMode &&
          subjectScoresJson == other.subjectScoresJson &&
          examAccumScore == other.examAccumScore &&
          lastGrade == other.lastGrade &&
          lastGradeRisk == other.lastGradeRisk &&
          eligibilityBlocked == other.eligibilityBlocked &&
          universityMajor == other.universityMajor &&
          majorSelected == other.majorSelected &&
          nextExamLabel == other.nextExamLabel &&
          weeksUntilNextExam == other.weeksUntilNextExam;
}

/// 기록 허브 "업적" 탭용(이월 부채 정리, 대화 2026-07-22) — content.db
/// `achievements`(정의, 아직 한 번도 안 달성됐어도 나와야 함)가 기준이고
/// slot.db `achievement_progress`(달성 여부·카운터)는 있으면 덧붙이는
/// 보조 조회. `unlock_achievement`(`data::repository`)가 이미 이 두
/// 테이블을 채우는 로직이라 여긴 순수 조회만.
class AchievementInfo {
  final String id;
  final String category;
  final String label;
  final bool achieved;
  final PlatformInt64? achievedDay;
  final PlatformInt64 counter;

  const AchievementInfo({
    required this.id,
    required this.category,
    required this.label,
    required this.achieved,
    this.achievedDay,
    required this.counter,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      category.hashCode ^
      label.hashCode ^
      achieved.hashCode ^
      achievedDay.hashCode ^
      counter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AchievementInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          category == other.category &&
          label == other.label &&
          achieved == other.achieved &&
          achievedDay == other.achievedDay &&
          counter == other.counter;
}

/// 매치 화면 "타자 정보" 카드(대화 2026-07-25, 좌/우 레이아웃 재설계)용 —
/// `MatchStepInfo_AwaitingPitch.batter_id`는 raw npc id뿐이라 이름·능력치를
/// 못 보여줬다. `npc.stats`가 이미 컨택/파워/선구안을 갖고 있어(§01_선수_능력치)
/// 원라이너 조회로 충분 — 새 시뮬레이션 로직 없음.
class BatterProfileInfo {
  final String name;
  final double contact;
  final double power;
  final double eye;

  /// 타석 손잡이 원문("좌타"/"우타"/"양타", `npc.handedness`, migration v16)
  /// — 매치 화면에서 타자를 홈플레이트 좌/우 타석 중 어디에 그릴지
  /// 정하는 데 쓴다(대화 2026-07-25). 스위치 히터(양타)는 Dart가 임의로
  /// 한쪽(우타석)을 고르면 됨 — 실제 어느 쪽으로 타석에 섰는지는
  /// 엔진이 구분해 시뮬레이션하지 않는다.
  final String handedness;

  const BatterProfileInfo({
    required this.name,
    required this.contact,
    required this.power,
    required this.eye,
    required this.handedness,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      contact.hashCode ^
      power.hashCode ^
      eye.hashCode ^
      handedness.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatterProfileInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          contact == other.contact &&
          power == other.power &&
          eye == other.eye &&
          handedness == other.handedness;
}

/// 대회 브래킷 경기 한 줄 — `get_tournament_bracket`용. 팀 이름은 여기서
/// 안 채운다(UI가 이미 갖고 있는 팀 목록 조회 결과로 team_id→이름을
/// 매핑하는 게 중복 왕복 없이 더 싸다).
class BracketMatchInfo {
  final PlatformInt64 round;
  final String home;
  final String away;
  final PlatformInt64? homeRuns;
  final PlatformInt64? awayRuns;
  final PlatformInt64 day;

  const BracketMatchInfo({
    required this.round,
    required this.home,
    required this.away,
    this.homeRuns,
    this.awayRuns,
    required this.day,
  });

  @override
  int get hashCode =>
      round.hashCode ^
      home.hashCode ^
      away.hashCode ^
      homeRuns.hashCode ^
      awayRuns.hashCode ^
      day.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BracketMatchInfo &&
          runtimeType == other.runtimeType &&
          round == other.round &&
          home == other.home &&
          away == other.away &&
          homeRuns == other.homeRuns &&
          awayRuns == other.awayRuns &&
          day == other.day;
}

/// 홈 화면 실제 날짜 표시용(대화 2026-07-21) — `crate::calendar`를 그대로
/// 감싼다. 순수 계산이라 동기 호출.
class CalendarDateInfo {
  final PlatformInt64 year;
  final PlatformInt64 month;
  final PlatformInt64 day;

  const CalendarDateInfo({
    required this.year,
    required this.month,
    required this.day,
  });

  @override
  int get hashCode => year.hashCode ^ month.hashCode ^ day.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarDateInfo &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          month == other.month &&
          day == other.day;
}

/// 내 정보 "커리어" 탭용(대화 2026-07-21) — 입학·진로선택 갈림길(드래프트/
/// 대학/독립/입대)·병역 만료·은퇴를 시간순으로. `repository::log_career_event`
/// 가 남긴 `career_events`를 그대로 조회. 트레이드·계약은 이미
/// `getContractHistory`(`league_transactions`)에 있어 여기 안 겹침.
class CareerEventInfo {
  final PlatformInt64 day;
  final PlatformInt64 season;
  final String kind;
  final String detailJson;

  const CareerEventInfo({
    required this.day,
    required this.season,
    required this.kind,
    required this.detailJson,
  });

  @override
  int get hashCode =>
      day.hashCode ^ season.hashCode ^ kind.hashCode ^ detailJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CareerEventInfo &&
          runtimeType == other.runtimeType &&
          day == other.day &&
          season == other.season &&
          kind == other.kind &&
          detailJson == other.detailJson;
}

/// [08_은퇴](../../../04_UI기획/08_은퇴.md) §2 "통산 기록 대시보드" —
/// **등급 매김 없이 순수 숫자**(05_히스토리_엔딩.md §4 "인생은 점수로
/// 판정하지 않는다"). "최종 자산"(08_개인_재정)·업적·라이벌전 하이라이트는
/// 해당 시스템 자체가 아직 엔진에 없어 이번 스코프엔 없음(10_구현_Phase_계획.md
/// §6-28 스코프 판단 참고).
class CareerSummary {
  final PlatformInt64 games;
  final PlatformInt64 wins;
  final PlatformInt64 losses;
  final PlatformInt64 noDecisions;
  final PlatformInt64 strikeouts;
  final PlatformInt64 inningsPitched;
  final double era;

  /// Phase 6(§12 "기록 필드") — WHIP·K/9. 주인공은 항상 투수 아키타입
  /// (§7 DH)이라 타율 등 타격 스탯은 애초에 성립하지 않아, "개인기록"
  /// 탭엔 투수 기록만 노출한다.
  final double whip;
  final double kPer9;
  final bool retired;
  final String? retirementReason;

  const CareerSummary({
    required this.games,
    required this.wins,
    required this.losses,
    required this.noDecisions,
    required this.strikeouts,
    required this.inningsPitched,
    required this.era,
    required this.whip,
    required this.kPer9,
    required this.retired,
    this.retirementReason,
  });

  @override
  int get hashCode =>
      games.hashCode ^
      wins.hashCode ^
      losses.hashCode ^
      noDecisions.hashCode ^
      strikeouts.hashCode ^
      inningsPitched.hashCode ^
      era.hashCode ^
      whip.hashCode ^
      kPer9.hashCode ^
      retired.hashCode ^
      retirementReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CareerSummary &&
          runtimeType == other.runtimeType &&
          games == other.games &&
          wins == other.wins &&
          losses == other.losses &&
          noDecisions == other.noDecisions &&
          strikeouts == other.strikeouts &&
          inningsPitched == other.inningsPitched &&
          era == other.era &&
          whip == other.whip &&
          kPer9 == other.kPer9 &&
          retired == other.retired &&
          retirementReason == other.retirementReason;
}

/// 리그 탭 "진행중인 대회" 카드 하나(대화 2026-07-26) — `kind`가
/// `"league"`면 리그 순위 카드(팀마다 항상 1개), `"tournament"`면 이번
/// 시즌 참가한 대회 카드.
class CompetitionCardInfo {
  final String kind;
  final String id;
  final String name;
  final String statusSummary;
  final bool isEliminated;
  final bool isChampion;

  const CompetitionCardInfo({
    required this.kind,
    required this.id,
    required this.name,
    required this.statusSummary,
    required this.isEliminated,
    required this.isChampion,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      id.hashCode ^
      name.hashCode ^
      statusSummary.hashCode ^
      isEliminated.hashCode ^
      isChampion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompetitionCardInfo &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          id == other.id &&
          name == other.name &&
          statusSummary == other.statusSummary &&
          isEliminated == other.isEliminated &&
          isChampion == other.isChampion;
}

/// [03_기록](../../../04_UI기획/03_기록.md) §1 "경기 로그" 탭 — `game_log`는
/// 압축 없이 경기별 전체 보존(07_매치_엔진.md §12). `detail_json`은
/// `{"grade","runs_allowed","opponent"}`(`apply_protagonist_evaluation`
/// 참고).
class GameLogEntry {
  final String gameId;
  final PlatformInt64 season;
  final String detailJson;

  const GameLogEntry({
    required this.gameId,
    required this.season,
    required this.detailJson,
  });

  @override
  int get hashCode => gameId.hashCode ^ season.hashCode ^ detailJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameLogEntry &&
          runtimeType == other.runtimeType &&
          gameId == other.gameId &&
          season == other.season &&
          detailJson == other.detailJson;
}

/// 캐릭터 생성 "학교 선택" 상세 카드용 — [02_고교](../../../02_기획/리그팀/02_고교.md)
/// §3의 "전력★"은 실제로는 content.db에 옮겨진 적이 없는 설계문서
/// 전용값이라(확인 완료, 대화 2026-07-21), 대신 이미 시드된
/// `team_history.season_ranks`(최근 5시즌 순위)에서 별점을 계산한다 —
/// 시드마다 달라질 수 있는 "살아있는" 값이라 정적 문서값보다 게임
/// 데이터에 충실하다. `teams.stadium_id`(권역별 거점구장 공유 —
/// `content::load_team_groups_for_schedule`가 스케줄링에 쓰는 것과 동일
/// 그룹)로 묶은 뒤 그 안에서의 상대 순위로 별점을 매겨, 6팀 권역과
/// 20팀 권역을 공정하게 비교한다. `stadium_name`/`park_factor`는 그
/// 권역이 공유하는 거점구장 정보(`stadiums` 테이블) — 학교마다 고유
/// 구장이 아니라 같은 권역이면 값이 같다(대화 2026-07-21).
class HsSchoolDetail {
  final String teamId;
  final String name;
  final String region;
  final PlatformInt64 stars;
  final String seasonRanksJson;
  final String titlesJson;
  final String rivalsJson;
  final double budget;
  final String stadiumName;
  final String parkFactor;

  const HsSchoolDetail({
    required this.teamId,
    required this.name,
    required this.region,
    required this.stars,
    required this.seasonRanksJson,
    required this.titlesJson,
    required this.rivalsJson,
    required this.budget,
    required this.stadiumName,
    required this.parkFactor,
  });

  @override
  int get hashCode =>
      teamId.hashCode ^
      name.hashCode ^
      region.hashCode ^
      stars.hashCode ^
      seasonRanksJson.hashCode ^
      titlesJson.hashCode ^
      rivalsJson.hashCode ^
      budget.hashCode ^
      stadiumName.hashCode ^
      parkFactor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HsSchoolDetail &&
          runtimeType == other.runtimeType &&
          teamId == other.teamId &&
          name == other.name &&
          region == other.region &&
          stars == other.stars &&
          seasonRanksJson == other.seasonRanksJson &&
          titlesJson == other.titlesJson &&
          rivalsJson == other.rivalsJson &&
          budget == other.budget &&
          stadiumName == other.stadiumName &&
          parkFactor == other.parkFactor;
}

/// 메시지함(`inbox`) — I8 이전 첫 실사용(§6-64 부상 전조 경고, `process_protagonist_week`
/// 가 유일한 생산자). AI 콘텐츠 저작이 아니라 시스템이 직접 생성하는
/// 경고 메시지라 I8 의존 없음.
class InboxMessageInfo {
  final String id;
  final String kind;
  final String urgency;
  final bool read;
  final PlatformInt64 day;
  final String body;

  const InboxMessageInfo({
    required this.id,
    required this.kind,
    required this.urgency,
    required this.read,
    required this.day,
    required this.body,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      urgency.hashCode ^
      read.hashCode ^
      day.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InboxMessageInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          urgency == other.urgency &&
          read == other.read &&
          day == other.day &&
          body == other.body;
}

/// [03_기록](../../../04_UI기획/03_기록.md) §1 "부상·재활" 탭 —
/// `protagonist.injury.history`(08_부상_시스템.md §5, 부위·심각도·발생일).
/// **치료 선택·복귀 확정 시점은 이 로그에 없음** — `record_injury`가
/// 기록하는 `history` 항목은 발생 시점 스냅샷뿐이고, 치료법 확정
/// (`treat`)·완치(`clear_healed_injury`)는 `current` 필드만 갱신하고
/// `history`에 별도로 남기지 않는다(엔진 쪽에 그 로그를 추가하는 건
/// 이번 스코프 밖).
class InjuryLogEntry {
  final String part_;
  final String severity;
  final PlatformInt64 day;

  const InjuryLogEntry({
    required this.part_,
    required this.severity,
    required this.day,
  });

  @override
  int get hashCode => part_.hashCode ^ severity.hashCode ^ day.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InjuryLogEntry &&
          runtimeType == other.runtimeType &&
          part_ == other.part_ &&
          severity == other.severity &&
          day == other.day;
}

/// [03_기록](../../../04_UI기획/03_기록.md) §1 "계약·이력" 탭 — `league_transactions`
/// 중 `'contract'`(방출/체결, `process_protagonist_contract`·
/// `resolve_contract_nego`가 기록)·`'trade'`(`resolve_trade_decision`이
/// 기록) 종류만. `'champion'`(리그 전체 우승팀 기록)은 주인공 개인 이력이
/// 아니라 제외. **드래프트 로그는 없음** — 진로 갈림길(고교→프로 진입)
/// 자체가 엔진에 없어(§6-19에서 이미 확인) 드래프트 이벤트가 발생할
/// 수가 없다.
class LeagueTransactionEntry {
  final String id;
  final PlatformInt64 day;
  final String kind;
  final String detailJson;

  const LeagueTransactionEntry({
    required this.id,
    required this.day,
    required this.kind,
    required this.detailJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^ day.hashCode ^ kind.hashCode ^ detailJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LeagueTransactionEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          day == other.day &&
          kind == other.kind &&
          detailJson == other.detailJson;
}

/// `learnable_pitches` 조회 결과.
class LearnablePitchesInfo {
  /// 조건을 전부 충족해 바로 "신규 습득" 슬롯에 배정 가능한 구종.
  final List<String> eligible;

  /// `eligible`이 비었을 때만 채워지는, 조건 격차(충족 못한 조건들의
  /// (임계-현재) 합)가 가장 작은 다음 목표 하나.
  final LockedPitchInfo? nextCandidate;

  const LearnablePitchesInfo({required this.eligible, this.nextCandidate});

  @override
  int get hashCode => eligible.hashCode ^ nextCandidate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LearnablePitchesInfo &&
          runtimeType == other.runtimeType &&
          eligible == other.eligible &&
          nextCandidate == other.nextCandidate;
}

/// 아직 습득 조건을 다 못 채운 구종 하나 — 조건 줄 전부(이미 채운 것
/// 포함)를 담아 UI가 "다음 목표" 진행 상황을 여러 줄로 보여줄 수 있게 함.
class LockedPitchInfo {
  final String name;
  final List<PitchRequirementInfo> requirements;

  const LockedPitchInfo({required this.name, required this.requirements});

  @override
  int get hashCode => name.hashCode ^ requirements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LockedPitchInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          requirements == other.requirements;
}

@freezed
sealed class MatchStepInfo with _$MatchStepInfo {
  const MatchStepInfo._();

  const factory MatchStepInfo.awaitingPitch({
    required String batterId,
    required int balls,
    required int strikes,
    required bool highLeverage,
    required int inning,
    required bool topOfInning,
    required int outs,
    required List<bool> bases,
    required int homeRuns,
    required int awayRuns,

    /// 매치 화면 스태미나 게이지용(§6-N) — `PitcherChangeDecision.fatigue`
    /// 와 같은 값 출처.
    required double fatigue,
    required int pitchesThrown,

    /// 방금 전 타석의 인플레이 타구를 처리한 포지션(대화 2026-07-25,
    /// 매치 화면 수비 배지 하이라이트용) — 없으면(K/BB/HBP였거나
    /// 하프이닝이 막 시작됐으면) `None`.
    String? lastFielderPosition,

    /// `last_fielder_position`이 있을 때만 의미 있음 — 그 플레이가 실책이었는지.
    required bool lastPlayWasError,
  }) = MatchStepInfo_AwaitingPitch;
  const factory MatchStepInfo.gameOver({
    required int homeRuns,
    required int awayRuns,
  }) = MatchStepInfo_GameOver;

  /// 감독 개입(§8) 수동 모드 판단 요청 — `resolveChoice`에 `"유지"`/
  /// `"교체"`/`"맡기기"`를 응답해야 진행된다.
  const factory MatchStepInfo.pitcherChangeDecision({
    required int inning,
    required bool topOfInning,
    required int homeRuns,
    required int awayRuns,
    required int pitchesThrown,
    required double fatigue,
    required bool managerRecommendsPull,
  }) = MatchStepInfo_PitcherChangeDecision;
}

/// 매치 화면 박스스코어 라벨·주자 팀색·구장 그림(대화 2026-07-25) — 홈/
/// 원정 팀 id(Dart `hsSchoolColor`로 학교색 해시)와 홈 구장 id. 구장 id는
/// Dart가 `assets/stadium/{id}.gif`(구장별로 미리 색조 보정해둔 실사
/// 픽셀아트, content.db의 27개 stadium 행 하나당 하나씩) 자산 키로
/// 그대로 쓴다. 진행 중인 매치 세션이 없으면 `None`.
class MatchVenueInfo {
  final String homeTeamId;
  final String awayTeamId;
  final String stadiumId;

  const MatchVenueInfo({
    required this.homeTeamId,
    required this.awayTeamId,
    required this.stadiumId,
  });

  @override
  int get hashCode =>
      homeTeamId.hashCode ^ awayTeamId.hashCode ^ stadiumId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchVenueInfo &&
          runtimeType == other.runtimeType &&
          homeTeamId == other.homeTeamId &&
          awayTeamId == other.awayTeamId &&
          stadiumId == other.stadiumId;
}

/// 현재 진행일·시즌 — 전용 화면 없이도 "시즌종료"를 넘겼는지 UI가 배지로
/// 보여줄 수 있게 하는 최소 조회. `season`은 `season_meta`에 아직 한 번도
/// 안 쓰였으면(뉴게임 직후) 0.
class MetaStatusInfo {
  final PlatformInt64 currentDay;
  final PlatformInt64 season;

  const MetaStatusInfo({required this.currentDay, required this.season});

  @override
  int get hashCode => currentDay.hashCode ^ season.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetaStatusInfo &&
          runtimeType == other.runtimeType &&
          currentDay == other.currentDay &&
          season == other.season;
}

/// PendingAction 하나 — `04_게임루프.md` §3의 7종 중 지금 대기 중인 것.
/// `payload_json`은 타입별로 형태가 다른 JSON — Dart가 `kind`를 보고
/// 어떤 화면으로 갈지 고르고(전용화면은 후속 서브분), 그 화면이 필요한
/// 필드만 꺼내 쓴다.
class PendingActionInfo {
  final String id;
  final String kind;
  final String urgency;
  final PlatformInt64 createdDay;
  final String payloadJson;

  const PendingActionInfo({
    required this.id,
    required this.kind,
    required this.urgency,
    required this.createdDay,
    required this.payloadJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      urgency.hashCode ^
      createdDay.hashCode ^
      payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingActionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          urgency == other.urgency &&
          createdDay == other.createdDay &&
          payloadJson == other.payloadJson;
}

/// 습득 조건 한 줄(05_구종_시스템.md §3, 대화 2026-07-25) — `LockedPitchInfo`
/// 안에서만 쓰인다.
class PitchRequirementInfo {
  final String stat;
  final double minValue;
  final double currentValue;
  final bool met;

  const PitchRequirementInfo({
    required this.stat,
    required this.minValue,
    required this.currentValue,
    required this.met,
  });

  @override
  int get hashCode =>
      stat.hashCode ^ minValue.hashCode ^ currentValue.hashCode ^ met.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PitchRequirementInfo &&
          runtimeType == other.runtimeType &&
          stat == other.stat &&
          minValue == other.minValue &&
          currentValue == other.currentValue &&
          met == other.met;
}

/// 캐릭터 생성 화면 "투수 타입" 카드용(대화 2026-07-23) — 타입별 우세
/// 스탯(`exposed_stat_names()`의 9종 중 어느 것이 상단/중간 밴드인지)과
/// 습득 가능 2구종 후보 풀. `sim::protagonist::archetype_bands`/
/// `full_second_pitch_pool`을 그대로 노출 — RNG·DB 없는 순수 조회라 동기.
class PitcherArchetypeInfo {
  final String name;
  final List<String> primaryStats;
  final List<String> minorStats;
  final List<String> pitchPool;

  /// `exposed_stat_names()`와 같은 순서(9종)의 밴드 중앙값 — 카드
  /// 그래프 길이를 실제 생성값 근처로 보정하는 용도(대화 2026-07-23).
  final Float64List statMidpoints;

  const PitcherArchetypeInfo({
    required this.name,
    required this.primaryStats,
    required this.minorStats,
    required this.pitchPool,
    required this.statMidpoints,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      primaryStats.hashCode ^
      minorStats.hashCode ^
      pitchPool.hashCode ^
      statMidpoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PitcherArchetypeInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          primaryStats == other.primaryStats &&
          minorStats == other.minorStats &&
          pitchPool == other.pitchPool &&
          statMidpoints == other.statMidpoints;
}

/// 타자 시즌/통산 기록(Phase 5, 대화 2026-07-24) — `RosterPlayerInfo`와
/// 짝지어 로스터 화면에 성적을 보여주는 용도. `repository::NpcBattingLine`
/// 계산식을 그대로 노출.
class PlayerBattingStats {
  final String playerId;
  final String name;
  final PlatformInt64 plateAppearances;
  final PlatformInt64 atBats;
  final PlatformInt64 hits;
  final PlatformInt64 homeRuns;
  final PlatformInt64 walks;
  final PlatformInt64 rbi;
  final PlatformInt64 stolenBases;
  final PlatformInt64 caughtStealing;
  final PlatformInt64 strikeouts;
  final double battingAverage;
  final double onBasePercentage;
  final double sluggingPercentage;
  final double ops;

  const PlayerBattingStats({
    required this.playerId,
    required this.name,
    required this.plateAppearances,
    required this.atBats,
    required this.hits,
    required this.homeRuns,
    required this.walks,
    required this.rbi,
    required this.stolenBases,
    required this.caughtStealing,
    required this.strikeouts,
    required this.battingAverage,
    required this.onBasePercentage,
    required this.sluggingPercentage,
    required this.ops,
  });

  @override
  int get hashCode =>
      playerId.hashCode ^
      name.hashCode ^
      plateAppearances.hashCode ^
      atBats.hashCode ^
      hits.hashCode ^
      homeRuns.hashCode ^
      walks.hashCode ^
      rbi.hashCode ^
      stolenBases.hashCode ^
      caughtStealing.hashCode ^
      strikeouts.hashCode ^
      battingAverage.hashCode ^
      onBasePercentage.hashCode ^
      sluggingPercentage.hashCode ^
      ops.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerBattingStats &&
          runtimeType == other.runtimeType &&
          playerId == other.playerId &&
          name == other.name &&
          plateAppearances == other.plateAppearances &&
          atBats == other.atBats &&
          hits == other.hits &&
          homeRuns == other.homeRuns &&
          walks == other.walks &&
          rbi == other.rbi &&
          stolenBases == other.stolenBases &&
          caughtStealing == other.caughtStealing &&
          strikeouts == other.strikeouts &&
          battingAverage == other.battingAverage &&
          onBasePercentage == other.onBasePercentage &&
          sluggingPercentage == other.sluggingPercentage &&
          ops == other.ops;
}

/// `PlayerBattingStats`와 대칭인 투수 쪽.
class PlayerPitchingStats {
  final String playerId;
  final String name;
  final double inningsPitched;
  final PlatformInt64 strikeouts;
  final PlatformInt64 walks;
  final PlatformInt64 hitsAllowed;
  final PlatformInt64 runsAllowed;
  final PlatformInt64 saves;
  final PlatformInt64 holds;
  final PlatformInt64 errors;
  final double era;
  final double whip;
  final double kPer9;

  const PlayerPitchingStats({
    required this.playerId,
    required this.name,
    required this.inningsPitched,
    required this.strikeouts,
    required this.walks,
    required this.hitsAllowed,
    required this.runsAllowed,
    required this.saves,
    required this.holds,
    required this.errors,
    required this.era,
    required this.whip,
    required this.kPer9,
  });

  @override
  int get hashCode =>
      playerId.hashCode ^
      name.hashCode ^
      inningsPitched.hashCode ^
      strikeouts.hashCode ^
      walks.hashCode ^
      hitsAllowed.hashCode ^
      runsAllowed.hashCode ^
      saves.hashCode ^
      holds.hashCode ^
      errors.hashCode ^
      era.hashCode ^
      whip.hashCode ^
      kPer9.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerPitchingStats &&
          runtimeType == other.runtimeType &&
          playerId == other.playerId &&
          name == other.name &&
          inningsPitched == other.inningsPitched &&
          strikeouts == other.strikeouts &&
          walks == other.walks &&
          hitsAllowed == other.hitsAllowed &&
          runsAllowed == other.runsAllowed &&
          saves == other.saves &&
          holds == other.holds &&
          errors == other.errors &&
          era == other.era &&
          whip == other.whip &&
          kPer9 == other.kPer9;
}

/// 프리게임 브리핑([04_메시지함] 확장, 대화 2026-07-25) — `'game'` PendingAction
/// payload의 `game_id`/`home`/`away`를 그대로 받아 상대 선발·타선 상위·
/// 날씨·파크팩터를 미리 보여준다. 새 시뮬레이션 로직 없이 실제 매치가
/// 이미 쓰는 값들을 그대로 재사용: 선발은 `repository::load_starting_pitcher`
/// (로테이션 순번 그대로), 타선은 `repository::load_batting_lineup`(라인업
/// 순서 그대로) 중 컨택+파워 합산 상위 3명, 날씨는 실제 매치 세션이 쓰는
/// 것과 동일한 결정적 시드(`league_sub_seed(world_seed, "weather:{game_id}")`)
/// 로 미리 굴려서 매치가 실제로 시작될 때와 같은 값이 나오게 한다.
class PregameScoutingInfo {
  final String opponentTeamId;
  final String starterName;
  final double starterVelocity;
  final double starterControl;
  final double starterStuff;
  final List<ScoutedBatterInfo> topBatters;
  final String weather;
  final String parkFactorLabel;

  const PregameScoutingInfo({
    required this.opponentTeamId,
    required this.starterName,
    required this.starterVelocity,
    required this.starterControl,
    required this.starterStuff,
    required this.topBatters,
    required this.weather,
    required this.parkFactorLabel,
  });

  @override
  int get hashCode =>
      opponentTeamId.hashCode ^
      starterName.hashCode ^
      starterVelocity.hashCode ^
      starterControl.hashCode ^
      starterStuff.hashCode ^
      topBatters.hashCode ^
      weather.hashCode ^
      parkFactorLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PregameScoutingInfo &&
          runtimeType == other.runtimeType &&
          opponentTeamId == other.opponentTeamId &&
          starterName == other.starterName &&
          starterVelocity == other.starterVelocity &&
          starterControl == other.starterControl &&
          starterStuff == other.starterStuff &&
          topBatters == other.topBatters &&
          weather == other.weather &&
          parkFactorLabel == other.parkFactorLabel;
}

/// [01_내선수](../../../04_UI기획/01_내선수.md) 상태 탭 등에서 표시할 개인
/// 신체 정보 — 한 번도 설정 안 했으면(구세이브 포함) `None`.
class ProtagonistProfileInfo {
  final PlatformInt64 birthYear;
  final PlatformInt64 birthMonth;
  final PlatformInt64 birthDay;
  final double heightCm;
  final double weightKg;
  final String bloodType;
  final String hometown;
  final PlatformInt64 jerseyNumber;

  const ProtagonistProfileInfo({
    required this.birthYear,
    required this.birthMonth,
    required this.birthDay,
    required this.heightCm,
    required this.weightKg,
    required this.bloodType,
    required this.hometown,
    required this.jerseyNumber,
  });

  @override
  int get hashCode =>
      birthYear.hashCode ^
      birthMonth.hashCode ^
      birthDay.hashCode ^
      heightCm.hashCode ^
      weightKg.hashCode ^
      bloodType.hashCode ^
      hometown.hashCode ^
      jerseyNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtagonistProfileInfo &&
          runtimeType == other.runtimeType &&
          birthYear == other.birthYear &&
          birthMonth == other.birthMonth &&
          birthDay == other.birthDay &&
          heightCm == other.heightCm &&
          weightKg == other.weightKg &&
          bloodType == other.bloodType &&
          hometown == other.hometown &&
          jerseyNumber == other.jerseyNumber;
}

/// 주인공 상태 — 이름·능력치·라이브상태·계약·부상·보유구종·재정. 유연한
/// 블롭은 JSON 원시 통과(모듈 문서 참고) — Dart는 표시용으로만 읽는다.
/// `finance_json`은 개인 재정 최소 골격(08_개인_재정.md §5 "잔액"만,
/// 이월 부채 정리 대화 2026-07-22)의 표시용 필드.
class ProtagonistStatusInfo {
  final String name;
  final String statsJson;
  final String liveStateJson;
  final String contractJson;
  final String injuryJson;
  final String pitchesJson;
  final String financeJson;

  const ProtagonistStatusInfo({
    required this.name,
    required this.statsJson,
    required this.liveStateJson,
    required this.contractJson,
    required this.injuryJson,
    required this.pitchesJson,
    required this.financeJson,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      statsJson.hashCode ^
      liveStateJson.hashCode ^
      contractJson.hashCode ^
      injuryJson.hashCode ^
      pitchesJson.hashCode ^
      financeJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtagonistStatusInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          statsJson == other.statsJson &&
          liveStateJson == other.liveStateJson &&
          contractJson == other.contractJson &&
          injuryJson == other.injuryJson &&
          pitchesJson == other.pitchesJson &&
          financeJson == other.financeJson;
}

/// 기록 허브 "관계" 탭용(이월 부채 정리, 대화 2026-07-22) — 팀동료 관계
/// 데이터 자체가 엔진에 없어(§6-59 이후 반복 확인) **감독 관계만** 정직하게
/// 보여준다. 무소속(입대·미배정)이면 빈 목록.
class RelationshipInfo {
  final String npcId;
  final String name;
  final String role;
  final PlatformInt64 value;
  final PlatformInt64 arcStage;

  const RelationshipInfo({
    required this.npcId,
    required this.name,
    required this.role,
    required this.value,
    required this.arcStage,
  });

  @override
  int get hashCode =>
      npcId.hashCode ^
      name.hashCode ^
      role.hashCode ^
      value.hashCode ^
      arcStage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationshipInfo &&
          runtimeType == other.runtimeType &&
          npcId == other.npcId &&
          name == other.name &&
          role == other.role &&
          value == other.value &&
          arcStage == other.arcStage;
}

/// 로스터 한 명 — [02_리그](../../../04_UI기획/02_리그.md) §1. NPC는
/// S~D 등급이 없다(§1 "등급은 주인공 전용") — 능력치+포지션+보유구종만.
/// 개인 시즌/통산 성적은 `get_team_season_batting_stats`/`get_team_season_pitching_stats`/
/// `get_player_career_batting_stats`/`get_player_career_pitching_stats`(Phase 5,
/// 대화 2026-07-24)로 별도 조회.
class RosterPlayerInfo {
  final String id;
  final String name;
  final String position;
  final PlatformInt64 age;
  final String statsJson;
  final String? pitchesJson;

  const RosterPlayerInfo({
    required this.id,
    required this.name,
    required this.position,
    required this.age,
    required this.statsJson,
    this.pitchesJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      position.hashCode ^
      age.hashCode ^
      statsJson.hashCode ^
      pitchesJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RosterPlayerInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          position == other.position &&
          age == other.age &&
          statsJson == other.statsJson &&
          pitchesJson == other.pitchesJson;
}

/// [02_리그](../../../04_UI기획/02_리그.md) §2 일정 탭 — `team_id`의 전체
/// 스케줄(지난 결과 + 다가오는 경기). `result_json`이 `None`이면 아직 안
/// 열린 경기.
class ScheduleGameInfo {
  final String gameId;
  final PlatformInt64 day;
  final String home;
  final String away;
  final String? resultJson;

  const ScheduleGameInfo({
    required this.gameId,
    required this.day,
    required this.home,
    required this.away,
    this.resultJson,
  });

  @override
  int get hashCode =>
      gameId.hashCode ^
      day.hashCode ^
      home.hashCode ^
      away.hashCode ^
      resultJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduleGameInfo &&
          runtimeType == other.runtimeType &&
          gameId == other.gameId &&
          day == other.day &&
          home == other.home &&
          away == other.away &&
          resultJson == other.resultJson;
}

/// 프리게임 브리핑의 상대 타자 한 명(대화 2026-07-25) — `sim::match_sim::BatterStats`
/// 는 id만 갖고 있어(이름은 `npc` 테이블), 표시용으로 이름을 붙여 재포장.
class ScoutedBatterInfo {
  final String name;
  final double contact;
  final double power;
  final double eye;

  const ScoutedBatterInfo({
    required this.name,
    required this.contact,
    required this.power,
    required this.eye,
  });

  @override
  int get hashCode =>
      name.hashCode ^ contact.hashCode ^ power.hashCode ^ eye.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScoutedBatterInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          contact == other.contact &&
          power == other.power &&
          eye == other.eye;
}

/// [08_은퇴](../../../04_UI기획/08_은퇴.md) §2 "커리어 타임라인 그래프" —
/// `career_history`(시즌별 한 줄, `season_rollover`가 채움)를 그대로
/// 노출. `line_json`은 `{"games","wins","losses","no_decisions",
/// "strikeouts","innings_pitched","era"}` 형태.
class SeasonLine {
  final PlatformInt64 season;
  final String lineJson;

  const SeasonLine({required this.season, required this.lineJson});

  @override
  int get hashCode => season.hashCode ^ lineJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeasonLine &&
          runtimeType == other.runtimeType &&
          season == other.season &&
          lineJson == other.lineJson;
}

/// [02_데이터](../../../03_설계/02_데이터.md) §4 슬롯 수명주기 — 메인
/// 메뉴 "이어하기" 목록 한 줄. `slot::open`이 마이그레이션까지 자동
/// 적용하므로 구버전 슬롯도 그대로 읽힌다.
class SlotSummary {
  final String path;
  final String name;
  final PlatformInt64 currentDay;
  final PlatformInt64 season;
  final bool retired;

  const SlotSummary({
    required this.path,
    required this.name,
    required this.currentDay,
    required this.season,
    required this.retired,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      currentDay.hashCode ^
      season.hashCode ^
      retired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlotSummary &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          currentDay == other.currentDay &&
          season == other.season &&
          retired == other.retired;
}

/// [02_리그](../../../04_UI기획/02_리그.md) §3 순위 탭 — `league_id` 소속
/// 팀들의 승률 내림차순 순위. `standings.rank` 컬럼은 시즌 중엔 갱신 안
/// 되고 `season_rollover` 때만 확정되므로(`repository::update_standings`
/// 참고), 여기 `rank`는 이 조회 시점에 재계산한 값 — 정렬·표시 포맷팅일
/// 뿐 승패 판정 자체가 아니라 "UI가 해도 됨: 정렬"(03_구조.md §3)에 해당.
/// 로스터가 없어(방금 뉴게임 직후 등) `standings` 행이 아직 없는 팀은
/// 0승0패로 취급.
class StandingsRowInfo {
  final String teamId;
  final PlatformInt64 rank;
  final PlatformInt64 wins;
  final PlatformInt64 losses;
  final PlatformInt64 ties;

  const StandingsRowInfo({
    required this.teamId,
    required this.rank,
    required this.wins,
    required this.losses,
    required this.ties,
  });

  @override
  int get hashCode =>
      teamId.hashCode ^
      rank.hashCode ^
      wins.hashCode ^
      losses.hashCode ^
      ties.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StandingsRowInfo &&
          runtimeType == other.runtimeType &&
          teamId == other.teamId &&
          rank == other.rank &&
          wins == other.wins &&
          losses == other.losses &&
          ties == other.ties;
}

/// 캐릭터 생성 스텝3~4(지역·학교 선택)용 — 고교 리그 팀 전부와 팀특성
/// 3슬롯. 지역별 그룹핑·학교 카드 비주얼은 06_캐릭터생성.md 자체가
/// "열린 세부 — 아트 단계"로 이미 미뤄둔 항목이라, 이번 스코프는 평평한
/// 목록만 준다 — Dart가 `meta_json`에서 이름 등 표시 필드를 꺼내 쓴다.
class TeamOption {
  final String teamId;
  final String leagueId;
  final String metaJson;
  final String philosophy;
  final String resource;
  final String status;

  const TeamOption({
    required this.teamId,
    required this.leagueId,
    required this.metaJson,
    required this.philosophy,
    required this.resource,
    required this.status,
  });

  @override
  int get hashCode =>
      teamId.hashCode ^
      leagueId.hashCode ^
      metaJson.hashCode ^
      philosophy.hashCode ^
      resource.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TeamOption &&
          runtimeType == other.runtimeType &&
          teamId == other.teamId &&
          leagueId == other.leagueId &&
          metaJson == other.metaJson &&
          philosophy == other.philosophy &&
          resource == other.resource &&
          status == other.status;
}

class TournamentBracketInfo {
  final String kind;
  final String displayName;
  final String status;
  final String? champion;
  final List<BracketMatchInfo> matches;

  const TournamentBracketInfo({
    required this.kind,
    required this.displayName,
    required this.status,
    this.champion,
    required this.matches,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      displayName.hashCode ^
      status.hashCode ^
      champion.hashCode ^
      matches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TournamentBracketInfo &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          displayName == other.displayName &&
          status == other.status &&
          champion == other.champion &&
          matches == other.matches;
}

/// 현재 훈련 설정 — 한 번도 설정 안 했으면 `None`(§1 "훈련 계획을 아직
/// 안 짰다"는 자연스러운 초기 상태, `set_protagonist_training` 문서 참고).
class TrainingConfigInfo {
  final String primaryTraining;
  final String secondaryTraining;
  final String intensity;
  final String? newPitch;

  /// 기존 구종 마스터리업 대상(05_구종_시스템.md §2, 대화 2026-07-23) —
  /// `new_pitch`와 상호 배타.
  final String? masteryPitch;

  /// `new_pitch`/`mastery_pitch` 진행도(주 단위) — 둘 다 `None`이면 0.
  /// 화면에서 "N/M주 진행 중" 표시용.
  final PlatformInt64 pitchWeeks;

  const TrainingConfigInfo({
    required this.primaryTraining,
    required this.secondaryTraining,
    required this.intensity,
    this.newPitch,
    this.masteryPitch,
    required this.pitchWeeks,
  });

  @override
  int get hashCode =>
      primaryTraining.hashCode ^
      secondaryTraining.hashCode ^
      intensity.hashCode ^
      newPitch.hashCode ^
      masteryPitch.hashCode ^
      pitchWeeks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrainingConfigInfo &&
          runtimeType == other.runtimeType &&
          primaryTraining == other.primaryTraining &&
          secondaryTraining == other.secondaryTraining &&
          intensity == other.intensity &&
          newPitch == other.newPitch &&
          masteryPitch == other.masteryPitch &&
          pitchWeeks == other.pitchWeeks;
}

/// [06_훈련_시스템](../../../02_기획/육성코어/06_훈련_시스템.md) §2-1
/// 훈련종류 카탈로그(6종) — 훈련 탭이 스탯 드롭다운 대신 이 목록을
/// 주/보조 훈련 선택 카드로 보여준다. 각 항목의 `stats`는 그 훈련종류가
/// 영향을 주는 능력치 2개(순서 무관).
class TrainingTypeInfo {
  final String id;
  final String name;
  final List<String> stats;

  const TrainingTypeInfo({
    required this.id,
    required this.name,
    required this.stats,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ stats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrainingTypeInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          stats == other.stats;
}

/// [07_전환화면](../../../04_UI기획/07_전환화면.md) §5 "3옵션 비교표" —
/// `injuryTreatment` PendingAction의 `choice_id`로 그대로 쓸 수 있는
/// `name`(`resolve_choice`가 기대하는 정확한 문자열, `sim::injury::TREATMENTS`)
/// 과 함께 이탈기간(`sim::injury::treated_recovery_days`, 실제 계산값)·
/// 재발위험·완치도(08_부상_시스템.md §4 표의 정성적 설명 — 수술/재활/
/// 무리한복귀 셋 다 즉시-판정형이라 정확한 확률은 선택 시점(`treat`)에야
/// 나오므로 사전 비교표는 문서가 확정해둔 상대적 설명 문구로 표시).
/// 순수 계산이라 동기.
class TreatmentOption {
  final String name;
  final PlatformInt64 recoveryDays;
  final String riskLabel;
  final String recoveryQualityLabel;

  const TreatmentOption({
    required this.name,
    required this.recoveryDays,
    required this.riskLabel,
    required this.recoveryQualityLabel,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      recoveryDays.hashCode ^
      riskLabel.hashCode ^
      recoveryQualityLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TreatmentOption &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          recoveryDays == other.recoveryDays &&
          riskLabel == other.riskLabel &&
          recoveryQualityLabel == other.recoveryQualityLabel;
}
