// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'game.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `with_state_mut`, `with_state`, `world_seed`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GameState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// 뉴게임 — [07_주인공_생성](../../../02_기획/07_주인공_생성.md) §1의 7단계
/// 흐름 중 실제 데이터를 만드는 마지막 단계(스텝 1~6은 Dart 쪽 폼 상태일
/// 뿐 엔진 호출이 아님). 결정적 seed로 배경 세계(172팀 로스터+일정)를
/// 먼저 만든 뒤 주인공을 생성해 전역 세션에 올린다.
Future<void> newGame({
  required String contentDbPath,
  required PlatformInt64 canonicalSeed,
  required String name,
  required String handedness,
  required String schoolTeamId,
  required String archetype,
  String? secondPitch,
}) => RustLib.instance.api.crateApiGameNewGame(
  contentDbPath: contentDbPath,
  canonicalSeed: canonicalSeed,
  name: name,
  handedness: handedness,
  schoolTeamId: schoolTeamId,
  archetype: archetype,
  secondPitch: secondPitch,
);

/// 진행(Continue) — [04_게임루프](../../../03_설계/04_게임루프.md) §2
/// `advance()`를 그대로 노출. 정지점(새 PendingAction 또는 주인공 경기)
/// 까지 하루씩 전진한 뒤 대기 목록을 반환한다.
Future<List<PendingActionInfo>> advance() =>
    RustLib.instance.api.crateApiGameAdvance();

/// PendingAction 응답 — 타입별 `choice_id` 형식은
/// [04_게임루프](../../../03_설계/04_게임루프.md) §3·엔진 `resolve_choice`
/// 문서 참고(`game`: 모드 문자열, `pitch`: `"구종:코스"`, `injuryTreatment`:
/// 치료법, `contractNego`: `"accept:team_id"`/`"counter:team_id:금액"`/
/// `"reject"`, `tradeDecision`: `"accept"`/`"reject"`). 결과가 `Some`이면
/// 매치가 계속 진행 중이라는 뜻 — Dart는 `AwaitingPitch`면 다음 1구를
/// 위해 다시 이 함수를 호출하고, `GameOver`면 경기 요약으로 넘어간다.
Future<MatchStepInfo?> resolveChoice({
  required String actionId,
  required String choiceId,
}) => RustLib.instance.api.crateApiGameResolveChoice(
  actionId: actionId,
  choiceId: choiceId,
);

Future<ProtagonistStatusInfo> getProtagonistStatus() =>
    RustLib.instance.api.crateApiGameGetProtagonistStatus();

/// 지금 세션의 미해결 PendingAction 전체 — 화면 재진입(예: 매치 중 다른
/// 탭 갔다가 복귀) 시 재조회용. `advance`/`resolve_choice`가 반환하는
/// 목록과 항상 같은 소스(`pending_actions` 테이블)를 본다.
Future<List<PendingActionInfo>> getPendingActions() =>
    RustLib.instance.api.crateApiGameGetPendingActions();

Future<MetaStatusInfo> getMetaStatus() =>
    RustLib.instance.api.crateApiGameGetMetaStatus();

/// 1구 조작 집중뷰의 3×3 코스 그리드 버튼 이름 — `sim::pitch::Course`의
/// 9개 값 그대로(`resolve_choice`의 `"구종:코스"` choice_id에 이 이름을
/// 그대로 넣으면 된다). 순수 계산(I/O·락 없음)이라 동기 호출로 둔다 —
/// Dart 쪽에서 `FutureBuilder` 없이 바로 리스트를 쓸 수 있다.
List<String> courseNames() => RustLib.instance.api.crateApiGameCourseNames();

Future<List<TeamOption>> listHsTeams({required String contentDbPath}) =>
    RustLib.instance.api.crateApiGameListHsTeams(contentDbPath: contentDbPath);

/// 지금 세션(전역 상태가 이미 content_conn을 들고 있음)에서 주인공의
/// 현재 소속팀 정보 — [01_내선수](../../../04_UI기획/01_내선수.md) 상단
/// 요약바의 "소속팀" 표시용. 무소속(FA·아직 프로 미진입)이면 `None`.
Future<TeamOption?> getCurrentTeamInfo() =>
    RustLib.instance.api.crateApiGameGetCurrentTeamInfo();

/// [06_훈련_시스템](../../../02_기획/육성코어/06_훈련_시스템.md) §2 능력치
/// 노출 스탯 9종 — 훈련 탭의 주/보조 슬롯 드롭다운용. 순수 상수라 동기.
List<String> exposedStatNames() =>
    RustLib.instance.api.crateApiGameExposedStatNames();

/// §4 강도 다이얼 3단계 — 순수 상수라 동기.
List<String> trainingIntensityNames() =>
    RustLib.instance.api.crateApiGameTrainingIntensityNames();

Future<TrainingConfigInfo?> getTrainingConfig() =>
    RustLib.instance.api.crateApiGameGetTrainingConfig();

/// 훈련 슬롯 설정 — [01_내선수](../../../04_UI기획/01_내선수.md) §3 훈련
/// 탭이 호출. `repository::set_protagonist_training`을 그대로 감싼다(구종
/// 슬롯·신규 습득은 이번 서브분 스코프 밖 — 전체 구종 카탈로그를 조회할
/// 엔진 쿼리가 아직 없어 `new_pitch`는 항상 `None`으로 고정).
Future<void> setTraining({
  required String primaryStat,
  required String secondaryStat1,
  required String secondaryStat2,
  required String intensity,
}) => RustLib.instance.api.crateApiGameSetTraining(
  primaryStat: primaryStat,
  secondaryStat1: secondaryStat1,
  secondaryStat2: secondaryStat2,
  intensity: intensity,
);

@freezed
sealed class MatchStepInfo with _$MatchStepInfo {
  const MatchStepInfo._();

  const factory MatchStepInfo.awaitingPitch({
    required String batterId,
    required int balls,
    required int strikes,
    required bool highLeverage,
  }) = MatchStepInfo_AwaitingPitch;
  const factory MatchStepInfo.gameOver({
    required int homeRuns,
    required int awayRuns,
  }) = MatchStepInfo_GameOver;
}

/// 현재 진행일·시즌 — 전용 화면 없이도 "시즌종료"를 넘겼는지 UI가 배지로
/// 보여줄 수 있게 하는 최소 조회. `season`은 `season_meta`에 아직 한 번도
/// 안 쓰였으면(뉴게임 직후) 0.
class MetaStatusInfo {
  final PlatformInt64 currentDay;
  final PlatformInt64 season;

  const MetaStatusInfo({required this.currentDay, required this.season});

  @override
  int get hashCode => currentDay.hashCode ^ season.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetaStatusInfo &&
          runtimeType == other.runtimeType &&
          currentDay == other.currentDay &&
          season == other.season;
}

/// PendingAction 하나 — `04_게임루프.md` §3의 7종 중 지금 대기 중인 것.
/// `payload_json`은 타입별로 형태가 다른 JSON — Dart가 `kind`를 보고
/// 어떤 화면으로 갈지 고르고(전용화면은 후속 서브분), 그 화면이 필요한
/// 필드만 꺼내 쓴다.
class PendingActionInfo {
  final String id;
  final String kind;
  final String urgency;
  final PlatformInt64 createdDay;
  final String payloadJson;

  const PendingActionInfo({
    required this.id,
    required this.kind,
    required this.urgency,
    required this.createdDay,
    required this.payloadJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      urgency.hashCode ^
      createdDay.hashCode ^
      payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingActionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          urgency == other.urgency &&
          createdDay == other.createdDay &&
          payloadJson == other.payloadJson;
}

/// 주인공 상태 — 이름·능력치·라이브상태·계약·부상·보유구종. 유연한
/// 블롭은 JSON 원시 통과(모듈 문서 참고) — Dart는 표시용으로만 읽는다.
class ProtagonistStatusInfo {
  final String name;
  final String statsJson;
  final String liveStateJson;
  final String contractJson;
  final String injuryJson;
  final String pitchesJson;

  const ProtagonistStatusInfo({
    required this.name,
    required this.statsJson,
    required this.liveStateJson,
    required this.contractJson,
    required this.injuryJson,
    required this.pitchesJson,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      statsJson.hashCode ^
      liveStateJson.hashCode ^
      contractJson.hashCode ^
      injuryJson.hashCode ^
      pitchesJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtagonistStatusInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          statsJson == other.statsJson &&
          liveStateJson == other.liveStateJson &&
          contractJson == other.contractJson &&
          injuryJson == other.injuryJson &&
          pitchesJson == other.pitchesJson;
}

/// 캐릭터 생성 스텝3~4(지역·학교 선택)용 — 고교 리그 팀 전부와 팀특성
/// 3슬롯. 지역별 그룹핑·학교 카드 비주얼은 06_캐릭터생성.md 자체가
/// "열린 세부 — 아트 단계"로 이미 미뤄둔 항목이라, 이번 스코프는 평평한
/// 목록만 준다 — Dart가 `meta_json`에서 이름 등 표시 필드를 꺼내 쓴다.
class TeamOption {
  final String teamId;
  final String metaJson;
  final String philosophy;
  final String resource;
  final String status;

  const TeamOption({
    required this.teamId,
    required this.metaJson,
    required this.philosophy,
    required this.resource,
    required this.status,
  });

  @override
  int get hashCode =>
      teamId.hashCode ^
      metaJson.hashCode ^
      philosophy.hashCode ^
      resource.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TeamOption &&
          runtimeType == other.runtimeType &&
          teamId == other.teamId &&
          metaJson == other.metaJson &&
          philosophy == other.philosophy &&
          resource == other.resource &&
          status == other.status;
}

/// 현재 훈련 설정 — 한 번도 설정 안 했으면 `None`(§1 "훈련 계획을 아직
/// 안 짰다"는 자연스러운 초기 상태, `set_protagonist_training` 문서 참고).
class TrainingConfigInfo {
  final String primaryStat;
  final List<String> secondaryStats;
  final String intensity;
  final String? newPitch;

  const TrainingConfigInfo({
    required this.primaryStat,
    required this.secondaryStats,
    required this.intensity,
    this.newPitch,
  });

  @override
  int get hashCode =>
      primaryStat.hashCode ^
      secondaryStats.hashCode ^
      intensity.hashCode ^
      newPitch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrainingConfigInfo &&
          runtimeType == other.runtimeType &&
          primaryStat == other.primaryStat &&
          secondaryStats == other.secondaryStats &&
          intensity == other.intensity &&
          newPitch == other.newPitch;
}
