// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/game.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1647274868;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'engine',
        ioDirectory: '../engine/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<PendingActionInfo>> crateApiGameAdvance();

  Future<CareerSummary> crateApiGameCareerSummary();

  Future<List<SeasonLine>> crateApiGameCareerTimeline();

  List<String> crateApiGameCourseNames();

  Future<void> crateApiGameDeclareRetirement();

  List<String> crateApiGameExposedStatNames();

  Future<List<LeagueTransactionEntry>> crateApiGameGetContractHistory();

  Future<TeamOption?> crateApiGameGetCurrentTeamInfo();

  Future<List<GameLogEntry>> crateApiGameGetGameLog();

  Future<List<InjuryLogEntry>> crateApiGameGetInjuryHistory();

  Future<MetaStatusInfo> crateApiGameGetMetaStatus();

  Future<List<PendingActionInfo>> crateApiGameGetPendingActions();

  Future<ProtagonistStatusInfo> crateApiGameGetProtagonistStatus();

  Future<List<StandingsRowInfo>> crateApiGameGetStandings({
    required String leagueId,
  });

  Future<String?> crateApiGameGetTeamRivals({required String teamId});

  Future<List<ScheduleGameInfo>> crateApiGameGetTeamSchedule({
    required String teamId,
  });

  Future<TrainingConfigInfo?> crateApiGameGetTrainingConfig();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<List<TeamOption>> crateApiGameListHsTeams({
    required String contentDbPath,
  });

  Future<List<RosterPlayerInfo>> crateApiGameListRoster({
    required String teamId,
  });

  Future<List<TeamOption>> crateApiGameListTeams({String? leagueId});

  Future<void> crateApiGameNewGame({
    required String contentDbPath,
    required PlatformInt64 canonicalSeed,
    required String name,
    required String handedness,
    required String schoolTeamId,
    required String archetype,
    String? secondPitch,
  });

  Future<MatchStepInfo?> crateApiGameResolveChoice({
    required String actionId,
    required String choiceId,
  });

  Future<void> crateApiGameSetTraining({
    required String primaryStat,
    required String secondaryStat1,
    required String secondaryStat2,
    required String intensity,
  });

  List<String> crateApiGameTrainingIntensityNames();

  List<TreatmentOption> crateApiGameTreatmentOptions({
    required String severity,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<PendingActionInfo>> crateApiGameAdvance() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pending_action_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameAdvanceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameAdvanceConstMeta =>
      const TaskConstMeta(debugName: "advance", argNames: []);

  @override
  Future<CareerSummary> crateApiGameCareerSummary() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_career_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameCareerSummaryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameCareerSummaryConstMeta =>
      const TaskConstMeta(debugName: "career_summary", argNames: []);

  @override
  Future<List<SeasonLine>> crateApiGameCareerTimeline() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_season_line,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameCareerTimelineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameCareerTimelineConstMeta =>
      const TaskConstMeta(debugName: "career_timeline", argNames: []);

  @override
  List<String> crateApiGameCourseNames() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameCourseNamesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameCourseNamesConstMeta =>
      const TaskConstMeta(debugName: "course_names", argNames: []);

  @override
  Future<void> crateApiGameDeclareRetirement() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameDeclareRetirementConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameDeclareRetirementConstMeta =>
      const TaskConstMeta(debugName: "declare_retirement", argNames: []);

  @override
  List<String> crateApiGameExposedStatNames() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameExposedStatNamesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameExposedStatNamesConstMeta =>
      const TaskConstMeta(debugName: "exposed_stat_names", argNames: []);

  @override
  Future<List<LeagueTransactionEntry>> crateApiGameGetContractHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_league_transaction_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetContractHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetContractHistoryConstMeta =>
      const TaskConstMeta(debugName: "get_contract_history", argNames: []);

  @override
  Future<TeamOption?> crateApiGameGetCurrentTeamInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_team_option,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetCurrentTeamInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetCurrentTeamInfoConstMeta =>
      const TaskConstMeta(debugName: "get_current_team_info", argNames: []);

  @override
  Future<List<GameLogEntry>> crateApiGameGetGameLog() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_game_log_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetGameLogConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetGameLogConstMeta =>
      const TaskConstMeta(debugName: "get_game_log", argNames: []);

  @override
  Future<List<InjuryLogEntry>> crateApiGameGetInjuryHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_injury_log_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetInjuryHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetInjuryHistoryConstMeta =>
      const TaskConstMeta(debugName: "get_injury_history", argNames: []);

  @override
  Future<MetaStatusInfo> crateApiGameGetMetaStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_meta_status_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetMetaStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetMetaStatusConstMeta =>
      const TaskConstMeta(debugName: "get_meta_status", argNames: []);

  @override
  Future<List<PendingActionInfo>> crateApiGameGetPendingActions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pending_action_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetPendingActionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetPendingActionsConstMeta =>
      const TaskConstMeta(debugName: "get_pending_actions", argNames: []);

  @override
  Future<ProtagonistStatusInfo> crateApiGameGetProtagonistStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_protagonist_status_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetProtagonistStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetProtagonistStatusConstMeta =>
      const TaskConstMeta(debugName: "get_protagonist_status", argNames: []);

  @override
  Future<List<StandingsRowInfo>> crateApiGameGetStandings({
    required String leagueId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(leagueId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_standings_row_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetStandingsConstMeta,
        argValues: [leagueId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetStandingsConstMeta =>
      const TaskConstMeta(debugName: "get_standings", argNames: ["leagueId"]);

  @override
  Future<String?> crateApiGameGetTeamRivals({required String teamId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(teamId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetTeamRivalsConstMeta,
        argValues: [teamId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetTeamRivalsConstMeta =>
      const TaskConstMeta(debugName: "get_team_rivals", argNames: ["teamId"]);

  @override
  Future<List<ScheduleGameInfo>> crateApiGameGetTeamSchedule({
    required String teamId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(teamId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_schedule_game_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetTeamScheduleConstMeta,
        argValues: [teamId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetTeamScheduleConstMeta =>
      const TaskConstMeta(debugName: "get_team_schedule", argNames: ["teamId"]);

  @override
  Future<TrainingConfigInfo?> crateApiGameGetTrainingConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_training_config_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameGetTrainingConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameGetTrainingConfigConstMeta =>
      const TaskConstMeta(debugName: "get_training_config", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<TeamOption>> crateApiGameListHsTeams({
    required String contentDbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contentDbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_team_option,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameListHsTeamsConstMeta,
        argValues: [contentDbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameListHsTeamsConstMeta => const TaskConstMeta(
    debugName: "list_hs_teams",
    argNames: ["contentDbPath"],
  );

  @override
  Future<List<RosterPlayerInfo>> crateApiGameListRoster({
    required String teamId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(teamId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_roster_player_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameListRosterConstMeta,
        argValues: [teamId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameListRosterConstMeta =>
      const TaskConstMeta(debugName: "list_roster", argNames: ["teamId"]);

  @override
  Future<List<TeamOption>> crateApiGameListTeams({String? leagueId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(leagueId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_team_option,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameListTeamsConstMeta,
        argValues: [leagueId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameListTeamsConstMeta =>
      const TaskConstMeta(debugName: "list_teams", argNames: ["leagueId"]);

  @override
  Future<void> crateApiGameNewGame({
    required String contentDbPath,
    required PlatformInt64 canonicalSeed,
    required String name,
    required String handedness,
    required String schoolTeamId,
    required String archetype,
    String? secondPitch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contentDbPath, serializer);
          sse_encode_i_64(canonicalSeed, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(handedness, serializer);
          sse_encode_String(schoolTeamId, serializer);
          sse_encode_String(archetype, serializer);
          sse_encode_opt_String(secondPitch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameNewGameConstMeta,
        argValues: [
          contentDbPath,
          canonicalSeed,
          name,
          handedness,
          schoolTeamId,
          archetype,
          secondPitch,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameNewGameConstMeta => const TaskConstMeta(
    debugName: "new_game",
    argNames: [
      "contentDbPath",
      "canonicalSeed",
      "name",
      "handedness",
      "schoolTeamId",
      "archetype",
      "secondPitch",
    ],
  );

  @override
  Future<MatchStepInfo?> crateApiGameResolveChoice({
    required String actionId,
    required String choiceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(actionId, serializer);
          sse_encode_String(choiceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_match_step_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameResolveChoiceConstMeta,
        argValues: [actionId, choiceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameResolveChoiceConstMeta => const TaskConstMeta(
    debugName: "resolve_choice",
    argNames: ["actionId", "choiceId"],
  );

  @override
  Future<void> crateApiGameSetTraining({
    required String primaryStat,
    required String secondaryStat1,
    required String secondaryStat2,
    required String intensity,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(primaryStat, serializer);
          sse_encode_String(secondaryStat1, serializer);
          sse_encode_String(secondaryStat2, serializer);
          sse_encode_String(intensity, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGameSetTrainingConstMeta,
        argValues: [primaryStat, secondaryStat1, secondaryStat2, intensity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameSetTrainingConstMeta => const TaskConstMeta(
    debugName: "set_training",
    argNames: ["primaryStat", "secondaryStat1", "secondaryStat2", "intensity"],
  );

  @override
  List<String> crateApiGameTrainingIntensityNames() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameTrainingIntensityNamesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameTrainingIntensityNamesConstMeta =>
      const TaskConstMeta(debugName: "training_intensity_names", argNames: []);

  @override
  List<TreatmentOption> crateApiGameTreatmentOptions({
    required String severity,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(severity, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_treatment_option,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameTreatmentOptionsConstMeta,
        argValues: [severity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameTreatmentOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "treatment_options",
        argNames: ["severity"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MatchStepInfo dco_decode_box_autoadd_match_step_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_match_step_info(raw);
  }

  @protected
  TeamOption dco_decode_box_autoadd_team_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_team_option(raw);
  }

  @protected
  TrainingConfigInfo dco_decode_box_autoadd_training_config_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_training_config_info(raw);
  }

  @protected
  CareerSummary dco_decode_career_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return CareerSummary(
      games: dco_decode_i_64(arr[0]),
      wins: dco_decode_i_64(arr[1]),
      losses: dco_decode_i_64(arr[2]),
      noDecisions: dco_decode_i_64(arr[3]),
      strikeouts: dco_decode_i_64(arr[4]),
      inningsPitched: dco_decode_i_64(arr[5]),
      era: dco_decode_f_64(arr[6]),
      retired: dco_decode_bool(arr[7]),
      retirementReason: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GameLogEntry dco_decode_game_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GameLogEntry(
      gameId: dco_decode_String(arr[0]),
      season: dco_decode_i_64(arr[1]),
      detailJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  InjuryLogEntry dco_decode_injury_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return InjuryLogEntry(
      part_: dco_decode_String(arr[0]),
      severity: dco_decode_String(arr[1]),
      day: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  LeagueTransactionEntry dco_decode_league_transaction_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LeagueTransactionEntry(
      id: dco_decode_String(arr[0]),
      day: dco_decode_i_64(arr[1]),
      kind: dco_decode_String(arr[2]),
      detailJson: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<bool> dco_decode_list_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bool).toList();
  }

  @protected
  List<GameLogEntry> dco_decode_list_game_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_game_log_entry).toList();
  }

  @protected
  List<InjuryLogEntry> dco_decode_list_injury_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_injury_log_entry).toList();
  }

  @protected
  List<LeagueTransactionEntry> dco_decode_list_league_transaction_entry(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_league_transaction_entry)
        .toList();
  }

  @protected
  List<PendingActionInfo> dco_decode_list_pending_action_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pending_action_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RosterPlayerInfo> dco_decode_list_roster_player_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_roster_player_info).toList();
  }

  @protected
  List<ScheduleGameInfo> dco_decode_list_schedule_game_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_schedule_game_info).toList();
  }

  @protected
  List<SeasonLine> dco_decode_list_season_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_season_line).toList();
  }

  @protected
  List<StandingsRowInfo> dco_decode_list_standings_row_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_standings_row_info).toList();
  }

  @protected
  List<TeamOption> dco_decode_list_team_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_team_option).toList();
  }

  @protected
  List<TreatmentOption> dco_decode_list_treatment_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_treatment_option).toList();
  }

  @protected
  MatchStepInfo dco_decode_match_step_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MatchStepInfo_AwaitingPitch(
          batterId: dco_decode_String(raw[1]),
          balls: dco_decode_u_32(raw[2]),
          strikes: dco_decode_u_32(raw[3]),
          highLeverage: dco_decode_bool(raw[4]),
          inning: dco_decode_u_32(raw[5]),
          topOfInning: dco_decode_bool(raw[6]),
          outs: dco_decode_u_32(raw[7]),
          bases: dco_decode_list_bool(raw[8]),
          homeRuns: dco_decode_u_32(raw[9]),
          awayRuns: dco_decode_u_32(raw[10]),
        );
      case 1:
        return MatchStepInfo_GameOver(
          homeRuns: dco_decode_u_32(raw[1]),
          awayRuns: dco_decode_u_32(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  MetaStatusInfo dco_decode_meta_status_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MetaStatusInfo(
      currentDay: dco_decode_i_64(arr[0]),
      season: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  MatchStepInfo? dco_decode_opt_box_autoadd_match_step_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_match_step_info(raw);
  }

  @protected
  TeamOption? dco_decode_opt_box_autoadd_team_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_team_option(raw);
  }

  @protected
  TrainingConfigInfo? dco_decode_opt_box_autoadd_training_config_info(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_training_config_info(raw);
  }

  @protected
  PendingActionInfo dco_decode_pending_action_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PendingActionInfo(
      id: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      urgency: dco_decode_String(arr[2]),
      createdDay: dco_decode_i_64(arr[3]),
      payloadJson: dco_decode_String(arr[4]),
    );
  }

  @protected
  ProtagonistStatusInfo dco_decode_protagonist_status_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProtagonistStatusInfo(
      name: dco_decode_String(arr[0]),
      statsJson: dco_decode_String(arr[1]),
      liveStateJson: dco_decode_String(arr[2]),
      contractJson: dco_decode_String(arr[3]),
      injuryJson: dco_decode_String(arr[4]),
      pitchesJson: dco_decode_String(arr[5]),
    );
  }

  @protected
  RosterPlayerInfo dco_decode_roster_player_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RosterPlayerInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      position: dco_decode_String(arr[2]),
      age: dco_decode_i_64(arr[3]),
      statsJson: dco_decode_String(arr[4]),
      pitchesJson: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  ScheduleGameInfo dco_decode_schedule_game_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ScheduleGameInfo(
      gameId: dco_decode_String(arr[0]),
      day: dco_decode_i_64(arr[1]),
      home: dco_decode_String(arr[2]),
      away: dco_decode_String(arr[3]),
      resultJson: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  SeasonLine dco_decode_season_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SeasonLine(
      season: dco_decode_i_64(arr[0]),
      lineJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  StandingsRowInfo dco_decode_standings_row_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StandingsRowInfo(
      teamId: dco_decode_String(arr[0]),
      rank: dco_decode_i_64(arr[1]),
      wins: dco_decode_i_64(arr[2]),
      losses: dco_decode_i_64(arr[3]),
      ties: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  TeamOption dco_decode_team_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TeamOption(
      teamId: dco_decode_String(arr[0]),
      leagueId: dco_decode_String(arr[1]),
      metaJson: dco_decode_String(arr[2]),
      philosophy: dco_decode_String(arr[3]),
      resource: dco_decode_String(arr[4]),
      status: dco_decode_String(arr[5]),
    );
  }

  @protected
  TrainingConfigInfo dco_decode_training_config_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TrainingConfigInfo(
      primaryStat: dco_decode_String(arr[0]),
      secondaryStats: dco_decode_list_String(arr[1]),
      intensity: dco_decode_String(arr[2]),
      newPitch: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  TreatmentOption dco_decode_treatment_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TreatmentOption(
      name: dco_decode_String(arr[0]),
      recoveryDays: dco_decode_i_64(arr[1]),
      riskLabel: dco_decode_String(arr[2]),
      recoveryQualityLabel: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MatchStepInfo sse_decode_box_autoadd_match_step_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_match_step_info(deserializer));
  }

  @protected
  TeamOption sse_decode_box_autoadd_team_option(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_team_option(deserializer));
  }

  @protected
  TrainingConfigInfo sse_decode_box_autoadd_training_config_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_training_config_info(deserializer));
  }

  @protected
  CareerSummary sse_decode_career_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_games = sse_decode_i_64(deserializer);
    var var_wins = sse_decode_i_64(deserializer);
    var var_losses = sse_decode_i_64(deserializer);
    var var_noDecisions = sse_decode_i_64(deserializer);
    var var_strikeouts = sse_decode_i_64(deserializer);
    var var_inningsPitched = sse_decode_i_64(deserializer);
    var var_era = sse_decode_f_64(deserializer);
    var var_retired = sse_decode_bool(deserializer);
    var var_retirementReason = sse_decode_opt_String(deserializer);
    return CareerSummary(
      games: var_games,
      wins: var_wins,
      losses: var_losses,
      noDecisions: var_noDecisions,
      strikeouts: var_strikeouts,
      inningsPitched: var_inningsPitched,
      era: var_era,
      retired: var_retired,
      retirementReason: var_retirementReason,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GameLogEntry sse_decode_game_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gameId = sse_decode_String(deserializer);
    var var_season = sse_decode_i_64(deserializer);
    var var_detailJson = sse_decode_String(deserializer);
    return GameLogEntry(
      gameId: var_gameId,
      season: var_season,
      detailJson: var_detailJson,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  InjuryLogEntry sse_decode_injury_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_part_ = sse_decode_String(deserializer);
    var var_severity = sse_decode_String(deserializer);
    var var_day = sse_decode_i_64(deserializer);
    return InjuryLogEntry(
      part_: var_part_,
      severity: var_severity,
      day: var_day,
    );
  }

  @protected
  LeagueTransactionEntry sse_decode_league_transaction_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_day = sse_decode_i_64(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_detailJson = sse_decode_String(deserializer);
    return LeagueTransactionEntry(
      id: var_id,
      day: var_day,
      kind: var_kind,
      detailJson: var_detailJson,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <bool>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bool(deserializer));
    }
    return ans_;
  }

  @protected
  List<GameLogEntry> sse_decode_list_game_log_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GameLogEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_game_log_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<InjuryLogEntry> sse_decode_list_injury_log_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InjuryLogEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_injury_log_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<LeagueTransactionEntry> sse_decode_list_league_transaction_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LeagueTransactionEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_league_transaction_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<PendingActionInfo> sse_decode_list_pending_action_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PendingActionInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pending_action_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RosterPlayerInfo> sse_decode_list_roster_player_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RosterPlayerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_roster_player_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ScheduleGameInfo> sse_decode_list_schedule_game_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ScheduleGameInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_schedule_game_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<SeasonLine> sse_decode_list_season_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SeasonLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_season_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<StandingsRowInfo> sse_decode_list_standings_row_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StandingsRowInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_standings_row_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<TeamOption> sse_decode_list_team_option(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TeamOption>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_team_option(deserializer));
    }
    return ans_;
  }

  @protected
  List<TreatmentOption> sse_decode_list_treatment_option(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TreatmentOption>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_treatment_option(deserializer));
    }
    return ans_;
  }

  @protected
  MatchStepInfo sse_decode_match_step_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_batterId = sse_decode_String(deserializer);
        var var_balls = sse_decode_u_32(deserializer);
        var var_strikes = sse_decode_u_32(deserializer);
        var var_highLeverage = sse_decode_bool(deserializer);
        var var_inning = sse_decode_u_32(deserializer);
        var var_topOfInning = sse_decode_bool(deserializer);
        var var_outs = sse_decode_u_32(deserializer);
        var var_bases = sse_decode_list_bool(deserializer);
        var var_homeRuns = sse_decode_u_32(deserializer);
        var var_awayRuns = sse_decode_u_32(deserializer);
        return MatchStepInfo_AwaitingPitch(
          batterId: var_batterId,
          balls: var_balls,
          strikes: var_strikes,
          highLeverage: var_highLeverage,
          inning: var_inning,
          topOfInning: var_topOfInning,
          outs: var_outs,
          bases: var_bases,
          homeRuns: var_homeRuns,
          awayRuns: var_awayRuns,
        );
      case 1:
        var var_homeRuns = sse_decode_u_32(deserializer);
        var var_awayRuns = sse_decode_u_32(deserializer);
        return MatchStepInfo_GameOver(
          homeRuns: var_homeRuns,
          awayRuns: var_awayRuns,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  MetaStatusInfo sse_decode_meta_status_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_currentDay = sse_decode_i_64(deserializer);
    var var_season = sse_decode_i_64(deserializer);
    return MetaStatusInfo(currentDay: var_currentDay, season: var_season);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MatchStepInfo? sse_decode_opt_box_autoadd_match_step_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_match_step_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TeamOption? sse_decode_opt_box_autoadd_team_option(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_team_option(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TrainingConfigInfo? sse_decode_opt_box_autoadd_training_config_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_training_config_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PendingActionInfo sse_decode_pending_action_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_urgency = sse_decode_String(deserializer);
    var var_createdDay = sse_decode_i_64(deserializer);
    var var_payloadJson = sse_decode_String(deserializer);
    return PendingActionInfo(
      id: var_id,
      kind: var_kind,
      urgency: var_urgency,
      createdDay: var_createdDay,
      payloadJson: var_payloadJson,
    );
  }

  @protected
  ProtagonistStatusInfo sse_decode_protagonist_status_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_statsJson = sse_decode_String(deserializer);
    var var_liveStateJson = sse_decode_String(deserializer);
    var var_contractJson = sse_decode_String(deserializer);
    var var_injuryJson = sse_decode_String(deserializer);
    var var_pitchesJson = sse_decode_String(deserializer);
    return ProtagonistStatusInfo(
      name: var_name,
      statsJson: var_statsJson,
      liveStateJson: var_liveStateJson,
      contractJson: var_contractJson,
      injuryJson: var_injuryJson,
      pitchesJson: var_pitchesJson,
    );
  }

  @protected
  RosterPlayerInfo sse_decode_roster_player_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_position = sse_decode_String(deserializer);
    var var_age = sse_decode_i_64(deserializer);
    var var_statsJson = sse_decode_String(deserializer);
    var var_pitchesJson = sse_decode_opt_String(deserializer);
    return RosterPlayerInfo(
      id: var_id,
      name: var_name,
      position: var_position,
      age: var_age,
      statsJson: var_statsJson,
      pitchesJson: var_pitchesJson,
    );
  }

  @protected
  ScheduleGameInfo sse_decode_schedule_game_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gameId = sse_decode_String(deserializer);
    var var_day = sse_decode_i_64(deserializer);
    var var_home = sse_decode_String(deserializer);
    var var_away = sse_decode_String(deserializer);
    var var_resultJson = sse_decode_opt_String(deserializer);
    return ScheduleGameInfo(
      gameId: var_gameId,
      day: var_day,
      home: var_home,
      away: var_away,
      resultJson: var_resultJson,
    );
  }

  @protected
  SeasonLine sse_decode_season_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_season = sse_decode_i_64(deserializer);
    var var_lineJson = sse_decode_String(deserializer);
    return SeasonLine(season: var_season, lineJson: var_lineJson);
  }

  @protected
  StandingsRowInfo sse_decode_standings_row_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_teamId = sse_decode_String(deserializer);
    var var_rank = sse_decode_i_64(deserializer);
    var var_wins = sse_decode_i_64(deserializer);
    var var_losses = sse_decode_i_64(deserializer);
    var var_ties = sse_decode_i_64(deserializer);
    return StandingsRowInfo(
      teamId: var_teamId,
      rank: var_rank,
      wins: var_wins,
      losses: var_losses,
      ties: var_ties,
    );
  }

  @protected
  TeamOption sse_decode_team_option(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_teamId = sse_decode_String(deserializer);
    var var_leagueId = sse_decode_String(deserializer);
    var var_metaJson = sse_decode_String(deserializer);
    var var_philosophy = sse_decode_String(deserializer);
    var var_resource = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return TeamOption(
      teamId: var_teamId,
      leagueId: var_leagueId,
      metaJson: var_metaJson,
      philosophy: var_philosophy,
      resource: var_resource,
      status: var_status,
    );
  }

  @protected
  TrainingConfigInfo sse_decode_training_config_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_primaryStat = sse_decode_String(deserializer);
    var var_secondaryStats = sse_decode_list_String(deserializer);
    var var_intensity = sse_decode_String(deserializer);
    var var_newPitch = sse_decode_opt_String(deserializer);
    return TrainingConfigInfo(
      primaryStat: var_primaryStat,
      secondaryStats: var_secondaryStats,
      intensity: var_intensity,
      newPitch: var_newPitch,
    );
  }

  @protected
  TreatmentOption sse_decode_treatment_option(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_recoveryDays = sse_decode_i_64(deserializer);
    var var_riskLabel = sse_decode_String(deserializer);
    var var_recoveryQualityLabel = sse_decode_String(deserializer);
    return TreatmentOption(
      name: var_name,
      recoveryDays: var_recoveryDays,
      riskLabel: var_riskLabel,
      recoveryQualityLabel: var_recoveryQualityLabel,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_match_step_info(
    MatchStepInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_match_step_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_team_option(
    TeamOption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_team_option(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_training_config_info(
    TrainingConfigInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_training_config_info(self, serializer);
  }

  @protected
  void sse_encode_career_summary(CareerSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.games, serializer);
    sse_encode_i_64(self.wins, serializer);
    sse_encode_i_64(self.losses, serializer);
    sse_encode_i_64(self.noDecisions, serializer);
    sse_encode_i_64(self.strikeouts, serializer);
    sse_encode_i_64(self.inningsPitched, serializer);
    sse_encode_f_64(self.era, serializer);
    sse_encode_bool(self.retired, serializer);
    sse_encode_opt_String(self.retirementReason, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_game_log_entry(GameLogEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gameId, serializer);
    sse_encode_i_64(self.season, serializer);
    sse_encode_String(self.detailJson, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_injury_log_entry(
    InjuryLogEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.part_, serializer);
    sse_encode_String(self.severity, serializer);
    sse_encode_i_64(self.day, serializer);
  }

  @protected
  void sse_encode_league_transaction_entry(
    LeagueTransactionEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.day, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.detailJson, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bool(item, serializer);
    }
  }

  @protected
  void sse_encode_list_game_log_entry(
    List<GameLogEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_game_log_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_injury_log_entry(
    List<InjuryLogEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_injury_log_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_league_transaction_entry(
    List<LeagueTransactionEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_league_transaction_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pending_action_info(
    List<PendingActionInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pending_action_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_roster_player_info(
    List<RosterPlayerInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_roster_player_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_schedule_game_info(
    List<ScheduleGameInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_schedule_game_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_season_line(
    List<SeasonLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_season_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_standings_row_info(
    List<StandingsRowInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_standings_row_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_team_option(
    List<TeamOption> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_team_option(item, serializer);
    }
  }

  @protected
  void sse_encode_list_treatment_option(
    List<TreatmentOption> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_treatment_option(item, serializer);
    }
  }

  @protected
  void sse_encode_match_step_info(
    MatchStepInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MatchStepInfo_AwaitingPitch(
        batterId: final batterId,
        balls: final balls,
        strikes: final strikes,
        highLeverage: final highLeverage,
        inning: final inning,
        topOfInning: final topOfInning,
        outs: final outs,
        bases: final bases,
        homeRuns: final homeRuns,
        awayRuns: final awayRuns,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(batterId, serializer);
        sse_encode_u_32(balls, serializer);
        sse_encode_u_32(strikes, serializer);
        sse_encode_bool(highLeverage, serializer);
        sse_encode_u_32(inning, serializer);
        sse_encode_bool(topOfInning, serializer);
        sse_encode_u_32(outs, serializer);
        sse_encode_list_bool(bases, serializer);
        sse_encode_u_32(homeRuns, serializer);
        sse_encode_u_32(awayRuns, serializer);
      case MatchStepInfo_GameOver(
        homeRuns: final homeRuns,
        awayRuns: final awayRuns,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(homeRuns, serializer);
        sse_encode_u_32(awayRuns, serializer);
    }
  }

  @protected
  void sse_encode_meta_status_info(
    MetaStatusInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.currentDay, serializer);
    sse_encode_i_64(self.season, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_match_step_info(
    MatchStepInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_match_step_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_team_option(
    TeamOption? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_team_option(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_training_config_info(
    TrainingConfigInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_training_config_info(self, serializer);
    }
  }

  @protected
  void sse_encode_pending_action_info(
    PendingActionInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.urgency, serializer);
    sse_encode_i_64(self.createdDay, serializer);
    sse_encode_String(self.payloadJson, serializer);
  }

  @protected
  void sse_encode_protagonist_status_info(
    ProtagonistStatusInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.statsJson, serializer);
    sse_encode_String(self.liveStateJson, serializer);
    sse_encode_String(self.contractJson, serializer);
    sse_encode_String(self.injuryJson, serializer);
    sse_encode_String(self.pitchesJson, serializer);
  }

  @protected
  void sse_encode_roster_player_info(
    RosterPlayerInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.position, serializer);
    sse_encode_i_64(self.age, serializer);
    sse_encode_String(self.statsJson, serializer);
    sse_encode_opt_String(self.pitchesJson, serializer);
  }

  @protected
  void sse_encode_schedule_game_info(
    ScheduleGameInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gameId, serializer);
    sse_encode_i_64(self.day, serializer);
    sse_encode_String(self.home, serializer);
    sse_encode_String(self.away, serializer);
    sse_encode_opt_String(self.resultJson, serializer);
  }

  @protected
  void sse_encode_season_line(SeasonLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.season, serializer);
    sse_encode_String(self.lineJson, serializer);
  }

  @protected
  void sse_encode_standings_row_info(
    StandingsRowInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.teamId, serializer);
    sse_encode_i_64(self.rank, serializer);
    sse_encode_i_64(self.wins, serializer);
    sse_encode_i_64(self.losses, serializer);
    sse_encode_i_64(self.ties, serializer);
  }

  @protected
  void sse_encode_team_option(TeamOption self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.teamId, serializer);
    sse_encode_String(self.leagueId, serializer);
    sse_encode_String(self.metaJson, serializer);
    sse_encode_String(self.philosophy, serializer);
    sse_encode_String(self.resource, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_training_config_info(
    TrainingConfigInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.primaryStat, serializer);
    sse_encode_list_String(self.secondaryStats, serializer);
    sse_encode_String(self.intensity, serializer);
    sse_encode_opt_String(self.newPitch, serializer);
  }

  @protected
  void sse_encode_treatment_option(
    TreatmentOption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_i_64(self.recoveryDays, serializer);
    sse_encode_String(self.riskLabel, serializer);
    sse_encode_String(self.recoveryQualityLabel, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
