// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/game.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MatchStepInfo dco_decode_box_autoadd_match_step_info(dynamic raw);

  @protected
  ProtagonistProfileInfo dco_decode_box_autoadd_protagonist_profile_info(
    dynamic raw,
  );

  @protected
  TeamOption dco_decode_box_autoadd_team_option(dynamic raw);

  @protected
  TrainingConfigInfo dco_decode_box_autoadd_training_config_info(dynamic raw);

  @protected
  CalendarDateInfo dco_decode_calendar_date_info(dynamic raw);

  @protected
  CareerSummary dco_decode_career_summary(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GameLogEntry dco_decode_game_log_entry(dynamic raw);

  @protected
  HsSchoolDetail dco_decode_hs_school_detail(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InjuryLogEntry dco_decode_injury_log_entry(dynamic raw);

  @protected
  LeagueTransactionEntry dco_decode_league_transaction_entry(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<GameLogEntry> dco_decode_list_game_log_entry(dynamic raw);

  @protected
  List<HsSchoolDetail> dco_decode_list_hs_school_detail(dynamic raw);

  @protected
  List<InjuryLogEntry> dco_decode_list_injury_log_entry(dynamic raw);

  @protected
  List<LeagueTransactionEntry> dco_decode_list_league_transaction_entry(
    dynamic raw,
  );

  @protected
  List<PendingActionInfo> dco_decode_list_pending_action_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RosterPlayerInfo> dco_decode_list_roster_player_info(dynamic raw);

  @protected
  List<ScheduleGameInfo> dco_decode_list_schedule_game_info(dynamic raw);

  @protected
  List<SeasonLine> dco_decode_list_season_line(dynamic raw);

  @protected
  List<SlotSummary> dco_decode_list_slot_summary(dynamic raw);

  @protected
  List<StandingsRowInfo> dco_decode_list_standings_row_info(dynamic raw);

  @protected
  List<TeamOption> dco_decode_list_team_option(dynamic raw);

  @protected
  List<TreatmentOption> dco_decode_list_treatment_option(dynamic raw);

  @protected
  MatchStepInfo dco_decode_match_step_info(dynamic raw);

  @protected
  MetaStatusInfo dco_decode_meta_status_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MatchStepInfo? dco_decode_opt_box_autoadd_match_step_info(dynamic raw);

  @protected
  ProtagonistProfileInfo? dco_decode_opt_box_autoadd_protagonist_profile_info(
    dynamic raw,
  );

  @protected
  TeamOption? dco_decode_opt_box_autoadd_team_option(dynamic raw);

  @protected
  TrainingConfigInfo? dco_decode_opt_box_autoadd_training_config_info(
    dynamic raw,
  );

  @protected
  PendingActionInfo dco_decode_pending_action_info(dynamic raw);

  @protected
  ProtagonistProfileInfo dco_decode_protagonist_profile_info(dynamic raw);

  @protected
  ProtagonistStatusInfo dco_decode_protagonist_status_info(dynamic raw);

  @protected
  RosterPlayerInfo dco_decode_roster_player_info(dynamic raw);

  @protected
  ScheduleGameInfo dco_decode_schedule_game_info(dynamic raw);

  @protected
  SeasonLine dco_decode_season_line(dynamic raw);

  @protected
  SlotSummary dco_decode_slot_summary(dynamic raw);

  @protected
  StandingsRowInfo dco_decode_standings_row_info(dynamic raw);

  @protected
  TeamOption dco_decode_team_option(dynamic raw);

  @protected
  TrainingConfigInfo dco_decode_training_config_info(dynamic raw);

  @protected
  TreatmentOption dco_decode_treatment_option(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MatchStepInfo sse_decode_box_autoadd_match_step_info(
    SseDeserializer deserializer,
  );

  @protected
  ProtagonistProfileInfo sse_decode_box_autoadd_protagonist_profile_info(
    SseDeserializer deserializer,
  );

  @protected
  TeamOption sse_decode_box_autoadd_team_option(SseDeserializer deserializer);

  @protected
  TrainingConfigInfo sse_decode_box_autoadd_training_config_info(
    SseDeserializer deserializer,
  );

  @protected
  CalendarDateInfo sse_decode_calendar_date_info(SseDeserializer deserializer);

  @protected
  CareerSummary sse_decode_career_summary(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GameLogEntry sse_decode_game_log_entry(SseDeserializer deserializer);

  @protected
  HsSchoolDetail sse_decode_hs_school_detail(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InjuryLogEntry sse_decode_injury_log_entry(SseDeserializer deserializer);

  @protected
  LeagueTransactionEntry sse_decode_league_transaction_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<GameLogEntry> sse_decode_list_game_log_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<HsSchoolDetail> sse_decode_list_hs_school_detail(
    SseDeserializer deserializer,
  );

  @protected
  List<InjuryLogEntry> sse_decode_list_injury_log_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<LeagueTransactionEntry> sse_decode_list_league_transaction_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<PendingActionInfo> sse_decode_list_pending_action_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RosterPlayerInfo> sse_decode_list_roster_player_info(
    SseDeserializer deserializer,
  );

  @protected
  List<ScheduleGameInfo> sse_decode_list_schedule_game_info(
    SseDeserializer deserializer,
  );

  @protected
  List<SeasonLine> sse_decode_list_season_line(SseDeserializer deserializer);

  @protected
  List<SlotSummary> sse_decode_list_slot_summary(SseDeserializer deserializer);

  @protected
  List<StandingsRowInfo> sse_decode_list_standings_row_info(
    SseDeserializer deserializer,
  );

  @protected
  List<TeamOption> sse_decode_list_team_option(SseDeserializer deserializer);

  @protected
  List<TreatmentOption> sse_decode_list_treatment_option(
    SseDeserializer deserializer,
  );

  @protected
  MatchStepInfo sse_decode_match_step_info(SseDeserializer deserializer);

  @protected
  MetaStatusInfo sse_decode_meta_status_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MatchStepInfo? sse_decode_opt_box_autoadd_match_step_info(
    SseDeserializer deserializer,
  );

  @protected
  ProtagonistProfileInfo? sse_decode_opt_box_autoadd_protagonist_profile_info(
    SseDeserializer deserializer,
  );

  @protected
  TeamOption? sse_decode_opt_box_autoadd_team_option(
    SseDeserializer deserializer,
  );

  @protected
  TrainingConfigInfo? sse_decode_opt_box_autoadd_training_config_info(
    SseDeserializer deserializer,
  );

  @protected
  PendingActionInfo sse_decode_pending_action_info(
    SseDeserializer deserializer,
  );

  @protected
  ProtagonistProfileInfo sse_decode_protagonist_profile_info(
    SseDeserializer deserializer,
  );

  @protected
  ProtagonistStatusInfo sse_decode_protagonist_status_info(
    SseDeserializer deserializer,
  );

  @protected
  RosterPlayerInfo sse_decode_roster_player_info(SseDeserializer deserializer);

  @protected
  ScheduleGameInfo sse_decode_schedule_game_info(SseDeserializer deserializer);

  @protected
  SeasonLine sse_decode_season_line(SseDeserializer deserializer);

  @protected
  SlotSummary sse_decode_slot_summary(SseDeserializer deserializer);

  @protected
  StandingsRowInfo sse_decode_standings_row_info(SseDeserializer deserializer);

  @protected
  TeamOption sse_decode_team_option(SseDeserializer deserializer);

  @protected
  TrainingConfigInfo sse_decode_training_config_info(
    SseDeserializer deserializer,
  );

  @protected
  TreatmentOption sse_decode_treatment_option(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_match_step_info(
    MatchStepInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_protagonist_profile_info(
    ProtagonistProfileInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_team_option(
    TeamOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_training_config_info(
    TrainingConfigInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calendar_date_info(
    CalendarDateInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_career_summary(CareerSummary self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_game_log_entry(GameLogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_hs_school_detail(
    HsSchoolDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_injury_log_entry(
    InjuryLogEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_league_transaction_entry(
    LeagueTransactionEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_game_log_entry(
    List<GameLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hs_school_detail(
    List<HsSchoolDetail> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_injury_log_entry(
    List<InjuryLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_league_transaction_entry(
    List<LeagueTransactionEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pending_action_info(
    List<PendingActionInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_roster_player_info(
    List<RosterPlayerInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_schedule_game_info(
    List<ScheduleGameInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_season_line(
    List<SeasonLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slot_summary(
    List<SlotSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_standings_row_info(
    List<StandingsRowInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_team_option(
    List<TeamOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_treatment_option(
    List<TreatmentOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_match_step_info(MatchStepInfo self, SseSerializer serializer);

  @protected
  void sse_encode_meta_status_info(
    MetaStatusInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_match_step_info(
    MatchStepInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_protagonist_profile_info(
    ProtagonistProfileInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_team_option(
    TeamOption? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_training_config_info(
    TrainingConfigInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_action_info(
    PendingActionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_protagonist_profile_info(
    ProtagonistProfileInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_protagonist_status_info(
    ProtagonistStatusInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_roster_player_info(
    RosterPlayerInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_schedule_game_info(
    ScheduleGameInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_season_line(SeasonLine self, SseSerializer serializer);

  @protected
  void sse_encode_slot_summary(SlotSummary self, SseSerializer serializer);

  @protected
  void sse_encode_standings_row_info(
    StandingsRowInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_team_option(TeamOption self, SseSerializer serializer);

  @protected
  void sse_encode_training_config_info(
    TrainingConfigInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_treatment_option(
    TreatmentOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
